### ISSUE TITLE
HSTS headers not working with rocket-nginx.conf

### ISSUE THREAD

**Issue by dschallert** [maximejobin/rocket-nginx#10]
Hi,

after including the nginx-rocket.conf into my server{} block,  my HSTS headers somehow went missing on the response. 

Tried alot of things including placing the add_header at top, bottom of the server{} block or even in rocket-nginx.conf the again at top, bottom or in the if ($https = "on")  {} block.   Nothing did work.

Why?

        server {
                listen 10.0.0.2:443 ssl http2;
                server_name mycorp.com www.mycorp.com;
                access_log /var/log/nginx/access.log combined;
                error_log /var/log/nginx/error.log error;
                root /var/www/mycorp.com/;
                index index.php index.html index.htm;

                location / {
                        index index.php index.html index.htm;
                        try_files $uri $uri/ @rewrites;
                }

                location @rewrites {
                        rewrite ^ /index.php last;
                }

                
                ##########
                # SSL
                ##########
                ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
                ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA;
                ssl_prefer_server_ciphers on;
                ssl_ecdh_curve secp384r1;
                ssl_dhparam /etc/nginx/ssl/dhparam.pem;
                ssl_session_cache shared:SSL:20m;
                ssl_session_timeout 10m;
                ssl_certificate /etc/nginx/ssl/mycorp.com.crt;
                ssl_certificate_key /etc/nginx/ssl/mycorp.com.key;

                ##########
                # OCSP
                ##########
                ssl_stapling on;
                ssl_stapling_verify on;
                resolver 8.8.4.4 8.8.8.8;
                ssl_trusted_certificate /etc/nginx/ssl/mycorp.com.crt;

                ##########
                # HSTS
                ##########
                add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";

                ##########
                # PHP
                ##########
                location ~ ^(.+?\.php)(/.*)?$ {
                        try_files $1 = 404;
                        include /etc/nginx/fastcgi_params;
                        fastcgi_split_path_info ^(.+\.php)(/.+)\$;
                        fastcgi_param SCRIPT_FILENAME $document_root$1;
                        fastcgi_param PATH_INFO $2;
                        fastcgi_param HTTPS on;
                        fastcgi_pass unix:/var/run/php-fpm.socket;
                        fastcgi_index index.php;
                        add_header "X-WPFC-Cache" "MISS";
                }

                ##########
                # GZIP
                ##########
                gzip on;
                gzip_types text/css text/x-component application/x-javascript application/javascript text/javascript text/x-js text/richtext image/svg+xml text/plain text/xsd text/xsl text/xml image/x-icon;

                #################
                # YOAST SITEMAP
                #################
                rewrite ^/sitemap.xml$ /index.php?sitemap=1 last;
                rewrite ^/([^/]+?)-sitemap([0-9]+)?.xml$ /index.php?sitemap=$1&sitemap_n=$2 last;
                rewrite ^/main-sitemap\.xsl$ /index.php?xsl=main last;

                ##########
                # CORS
                ##########
                location ~ \.(ttf|ttc|otf|eot|woff|font.css)$ {
                        add_header Access-Control-Allow-Origin "*";
                }

                # Include wp-rocket nginx config
                include global/rocket-nginx.conf;

                # Include global restrictions config
                include global/restrictions.conf;
        }

Thanks
Dominic

**Comment by dschallert** [comment]
Ok, i've found a temporary solution by using this wordpress plugin:

https://wordpress.org/plugins/hsts/

Unfortunately the real cause of the issue remains uknown. There must be something with wp-rocket, which causes the header's to be removed.

**Comment by viktorix** [comment]
+1 on this. Have same issue.

**Comment by maximejobin** [comment]
I will try to replicate and see how this can be fixed in the next update.

References on HSTS:
https://en.wikipedia.org/wiki/SSL_stripping#SSL_stripping
https://developer.mozilla.org/en-US/docs/Web/Security/HTTP_strict_transport_security

**Comment by fgirardey** [comment]
+1 I got the same issue.

It result to a simple `A` note on SSL Labs

**Comment by dschallert** [comment]
I fixed it by adding

        if ($https = "on") {
          add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
        }


below line 99:

# Add header to HTML cached files
location ~ /wp-content/cache/wp-rocket/.*html$ {

**Comment by maximejobin** [comment]
Version 1.1 was released and addresses the HSTS issue.
A generic approach was taken.  A default value is used and you can alter it if you want.  You can see the release details : https://github.com/maximejobin/rocket-nginx/releases/tag/1.1

**Comment by Dibbyo456** [comment]
@maximejobin Was it really necessary to having the HSTS enabled by default along with includeSubDomains? 😕
One of my development site which loads under a subdomain without HTTPS.
I had to waste 1 hour just to debug how the HSTS became activated in the first place. 😕
