### ISSUE TITLE
how to configure sever block

### ISSUE THREAD

**Issue by rajuginne** [maximejobin/rocket-nginx#103]
server {
   
listen 80;;
    
  root /var/www/html/sweb.com/;
server_name sweb.com sweb.com;
include rocket-nginx/default.conf;
location / {
try_files $uri $uri/ /index.php?$args;
http2_push_preload on;
                }
  
  

location ~ \.php$ {
try_files $uri =404;

		include fastcgi_params;
	fastcgi_pass unix:/run/php/php7.2-fpm.sock;
fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        
	}

}

should i change 
**try_files $uri $uri/** /index.php?$args;

to 
try_files **/wp-content/cache/wp-rocket/$http_host/$cache_uri/index.html $uri/** /index.php?$args;

**Comment by rajuginne** [comment]
curl option get this

strict-transport-security: max-age=15768000; includeSubdomains; preload;
referrer-policy: no-referrer, strict-origin-when-cross-origin
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
x-rocket-nginx-serving-static: No
date: Wed, 13 Mar 2019 07:45:24 GMT
**x-page-speed**: 1.13.35.2-0
cache-control: max-age=0, no-cache

**Comment by maximejobin** [comment]
Here are the reasons why you would see a "No" (see the "Reasons for not serving a cached file" section):
https://github.com/maximejobin/rocket-nginx#debug

Otherwise, you should see a "Yes"... which means it is working.
