### ISSUE TITLE
HTTPS with Cloudflare flexible SSL

### ISSUE THREAD

**Issue by wysow** [maximejobin/rocket-nginx#14]
Hello,

It seems that the WP-Rocket plugin does generate a "https" cached file when accesing a website using Cloudflare Flexible SSL, even if the server is only using "http"...

So my question is, is it possible to optimize this on your side or should I report this on http://wp-rocket.me/support/ ?

**Comment by wysow** [comment]
After a little discussion with WP Rocket team it seems that is kind of an edge case as Cloudflare Flexible SSL is not a "real" SSL... Do you think it's possible to handle it in some way?

**Comment by maximejobin** [comment]
> is it possible to optimize this on your side

What do you want to optimize ?  Are you saying you want the configuration to avoid generating the HTTPS cache file ? If that's the case, the configuration cannot do that.

Please give more details on what is happening and what you are expecting.  I don't get what you are asking.

**Comment by wysow** [comment]
What I meant is that Cloudflare is acting like a proxy so the request is not really in "https" mode when getting on my server, so nginx tries to find the "http" version of the cached file, which is not generated as worpress thinks the server is in "https", so the cached file could not be served directly by nginx...

**Comment by maximejobin** [comment]
Do you have any plugins to "activate" HTTPS on your website ?

I talked with WP-Rocket and they said they were using the WordPress function `is_ssl()` to validate which file should be generated.  I checked the code and it's almost the samething Rocket-Nginx is doing.

If your web server receives an HTTP request, Rocket-Nginx will fetch the HTTP cached file.
If your web server receives an HTTPS request, Rocket-Nginx will fetch the HTTPS cached file.

The Flexible SSL from Cloudflare sends an HTTP request (and not HTTPS). That would explain why  Rocket-Nginx is trying to get the HTTP version of the cache file.

Now, the question is: why does WP-Rocket (or WordPress... as they use the `is_ssl()` funciton) thinks it is a HTTPS request.

Do you have any plugins linked to HTTPS/SSL ?   Can you send the logs of the request you receive from Cloudflare to your server (headers).

At this point, from my understanding, Rocket-Nginx is doing the right thing which is : trying to get the non-HTTPS cache file.

**Comment by wysow** [comment]
As I said we are talking about an edge case only when using Cloudflare Flexible SSL so, yes Rocket-Nginx is doing the right thing... I'm just trying to find a way to handle this nicely... But for now let's close this issue...

**Comment by maximejobin** [comment]
You do not have to close the issue if something is not working.  From my comprehension, I understand that the problem does not come from Rocket-Nginx.  I think it should work "as is" from WP-Rocket AND Rocket-Nginx.

If you can show a use case where it's not working as it should, I'll gladly take a look and find a solution.

**Comment by slayer49** [comment]
@wysow I use Cloudflare Flexible SSL and I just added the -https to the non https calls in rocket-nginx to work around this.    

However, I have another issue now which I am not sure is related.
