### ISSUE TITLE
Nginx on another server

### ISSUE THREAD

**Issue by Mirabis** [maximejobin/rocket-nginx#16]
Hi,

I've been testing some internal VM's and the process goes

WEB -> CLOUDFLARE -> ROUTER -> VM_NGINX -> VM_WORDPRESS 

NGINX = Bitnami nginx docker
WORDPRESS = wordpress apache docker image, 

Adding the script to my nginx proxy and changing $document_root into $http_host to avoid it from looking locally -> it creates links as:

```
"domain.nl/wp-content/cache/wp-rocket/domain.nl//wp-content/plugins/essential-grid/public/assets/css/settings.css?ver=d5190acd9a2750809b07eed7bbeac99f/index-https.html_gzip"````

Which seems okay, but no files are ever written in that directory. I checked the permissions etc, but I'm afraid it won't write cuz the proxy is on a remote server = is that right?

**Comment by maximejobin** [comment]
If you are using Nginx as a reverse proxy on a server **that is NOT** where your WordPress site is, the script won't work.

That said, you could simply use Nginx's reverse proxy caching with your configuration.

**Comment by Mirabis** [comment]
Ah Okey.. Would have to place nginx on that wordpress vm then.

Will have to check how nginx - nginx - wordpress impacts the speed.

Thanks for the quick response :)
