### ISSUE TITLE
Different wp-content file in each file

### ISSUE THREAD

**Issue by gnnpls** [maximejobin/rocket-nginx#17]
Hi. Thanks for the contribution.
I recently changed server and move to nginx server.
The problem now is that wp-rocket not working fine. I have already included your configuration into my server. But today I noticed that you are using the default wp-content path for serving the requests.
Is there a way to dynamic configure it for each site or now I have to include your code in every site's nginx conf separately?

**Comment by fgirardey** [comment]
The nature of Nginx is to be static for those configuration files.

Yes you have to configure in every sites those path 😕

**Comment by maximejobin** [comment]
Unfortunately, @fgirardey is right.  Each configuration file is independant so you can't set a variable in your "parent" configuration to call it in you "child" configuration with an "include" as you would do in PHP.

**Comment by maximejobin** [comment]
Your best bet is to edit [Line 60](https://github.com/maximejobin/rocket-nginx/blob/master/rocket-nginx.conf#L60). :(

**Comment by gnnpls** [comment]
Thanks for the reply.
Js minification & concentration not working at all, neither for the css.
The problem is that the minified files come with html code and the sites break:
<!DOCTYPE html>
<html lang="en-US" prefix="og: http://ogp.me/ns#" class="no-js" >

<head>
Have anyone seen something like that before?
I even tried and put all the code from then nginx rocket file to my site's nginx conf but still everything break.

**Comment by maximejobin** [comment]
Rocket-Nginx does not do minification and concatenation.  This job is done by WP-Rocket directly.  Please ask their support about this issue.

**Comment by gnnpls** [comment]
@maximejobin 
Thanks for the response. I have just asked them and I wait for their response. In my old non-nginx everything was working fine. But now I face this problem.
Anyway, Thanks for the contribution.
