### ISSUE TITLE
add_header Cache-Control public;

### ISSUE THREAD

**Issue by novakin** [maximejobin/rocket-nginx#19]
Why dont you add in all location block the following header ?

`add_header Cache-Control public;`

**Comment by maximejobin** [comment]
It might make sense for you but not for everyone.

> If the response is marked as “public” then it can be cached, even if it has HTTP authentication associated with it, and even when the response status code isn’t normally cacheable. Most of the time, “public” isn’t necessary, because explicit caching information (like “max-age”) indicates that the response is cacheable anyway.

It's the "even if it has HTTP authentication associated with it" that some people might not like.

**Comment by novakin** [comment]
Thx for the explanation
