### ISSUE TITLE
Nginx Admin + Apache + CentOS + WHM

### ISSUE THREAD

**Issue by brianjking** [maximejobin/rocket-nginx#2]
I'm using Nginx Admin to utilize Nginx with PHP-FCGI on a CentOS server running WebHostManager + cPanel. Can I still integrate your mods to enhance WP-Rocket without using the FPM handler?

**Comment by brianjking** [comment]
http://www.nginxcp.com/installation-instruction/

**Comment by maximejobin** [comment]
The provided configuration does not need FPM to work properly. It is a Nginx configuration to avoid passing the requests to FPM.  That being said, it was not tested when Nginx is used as a reverse proxy so the configuration may need to be adjusted.

**Comment by brianjking** [comment]
@maximejobin How about when using: https://github.com/nuevvo/engintron

Thanks!

**Comment by maximejobin** [comment]
As read on the project page: "Nginx setup in reverse caching proxy (web acceleration) mode for any static or PHP based website".  It is stil a reverse proxy.

It was not tested as a reverse proxy in any project.  Basically, if it uses both Apache and Nginx, it was not tested.
