### ISSUE TITLE
Support for WP-Rocket v2.7.x (multiple caches)

### ISSUE THREAD

**Issue by Whissi** [maximejobin/rocket-nginx#21]
Are you working on adding support for new WP-Rocket v2.7.x which added support for multiple caches based on UA? See http://wp-rocket.me/de/changelog/

**Comment by maximejobin** [comment]
I am looking into it.

**Comment by maximejobin** [comment]
I did not come up with a solution so far.  I am unsure what is the best way to handle the multiple caches functionality in Nginx.  I am not even sure it makes sense to check it at this level.  If you have a proposition, please submit a pull request.

**Comment by maximejobin** [comment]
Hey @jbma, do you guys only use "mobile" and "desktop" in your implementation.

I'd like to see how this can be done without asking users to to "install" a module in Nginx.  Will it be enough if a "is_mobile" is implemented in Rocket-Nginx ? If it's not mobile... then it's desktop. I want to make sure it's compatible with WP-Rocket.

[Jonathan told me](http://blog.wp-rocket.me/2-7-hoth/) you were using [Mobile detect](http://mobiledetect.net/).

I also saw [this page](http://docs.wp-rocket.me/article/663-mobile-cache-desktop-view-displayed-for-mobile-devices) on your website and wasn't proud that Rocket-Nginx could not handle things properly.

**Comment by jbma** [comment]
Hey @maximejobin yes we only use mobile and desktop with Mobile Detect class. 
The issue by implementing that on Nginx side, is if you change the option into WP Rocket admin, you will need to change it as well in your Nginx configuration.

What we do for Apache, to not having a huge htaccess will all the condition for mobile which will slow all request is to use to PHP fallback instead when the mobile option to creation a dedicaced cache is enabled.
That's why we recommend in our docs to do that as well with Nginx.

Thank you again for your great work on this conf file  👏

**Comment by maximejobin** [comment]
> The issue by implementing that on Nginx side, is if you change the option into WP Rocket admin, you will need to change it as well in your Nginx configuration.

Well, not really.  If there is a way to find out via the files on the disk, I could detect it.  This is what is done when a file is not put in cache: you don't generate it (and delete it if it exists on the disk).  The same thing could apply to mobile vs desktop.  If I detect it's a mobile device, I will check it the mobile file exists.  If not, fallback on desktop.

Can you point me to "how" and "where" you do your .htaccess bypass ?

**Comment by maximejobin** [comment]
UPDATE!!!

After sitting with Remy of WP-Rocket on July 24th, a solution was found.  To make it usable in Rocket-Nginx, the WP-Rocket team must add a new file in the cache folder to help Rocket-Nginx detect the proper configuration.

At this point, I am waiting for the implementation to release a newer version which will make Rocket-Nginx fully compatible with the latest version of WP-Rocket.

I have no ETA from them at this point.

**Comment by Mirabis** [comment]
```
2.8.11 25 August, 2016

    Enhancement: Specific cache for mobile option detection on NGINX
....
```

Is that the update you've been waiting for?

**Comment by maximejobin** [comment]
It is exactly the update I was waiting for! :-)

That is great.  I will finalize version 1.2 and make it available ASAP.

**Comment by maximejobin** [comment]
Please see version 1.2 (I pushed it to master) to validate that it solves the problem.

When you activate mobile cache, Rocket-Nginx simply does not serve the file directly.  The reason for this is that the process to determine if the visitor is on a mobile or not is to heavy to make it work in the Nginx configuration.  It is possible (I've coded it) but it does too many validations for each and every request (even for static files) that it makes no sense.
