### ISSUE TITLE
x-rocket-nginx-bypass:No

### ISSUE THREAD

**Issue by mende11eev** [maximejobin/rocket-nginx#23]
I have such stack:
 debian8+nginx+mariadb+opcache+memcached  and wprocket

i have insalled rocket-nginx debug show me:
x-rocket-nginx-bypass:No
x-rocket-nginx-file:/usr/share/nginx/html/ciplenok.com/wp-content/cache/wp-rocket/ciplenok.com//wp-content/themes/flatastic/js/jquery.raty.min.js/index-https.html_gzip ( and others files)
x-rocket-nginx-reason:File not cached

 my site: ciplenok.com

What am i suppose to do to enable your plugin?

**Comment by maximejobin** [comment]
That is normal.  You are checking for a JavaScript file.  This is not cached the same way by WP-Rocket.  You must check with your pages.

If you check with : http://ciplenok.com

You get this (which is exactly what you are supposed to get!):

    x-rocket-nginx-bypass:Yes
    x-rocket-nginx-file:/usr/share/nginx/html/ciplenok.com/wp-content/cache/wp-rocket/ciplenok.com///index-https.html_gzip
    x-rocket-nginx-reason:/wp-content/cache/wp-rocket/ciplenok.com///index-https.html_gzip
