### ISSUE TITLE
More headers with this conf?

### ISSUE THREAD

**Issue by DavidRSW** [maximejobin/rocket-nginx#24]
When I use this conf, other headers (as X-XSS, X-Frame, X-Content, Fastcgi-cache...) disappear.

How to include all headers with this conf?

Thanks.

**Comment by maximejobin** [comment]
You can see the reason here: http://serverfault.com/a/431189/113095

The answer to your question is that you have to modify Rocket-Nginx configuration to make it work.  The thing is that the script needs to alter your headers, for instance, if a gzip version is served.

There is no easy solution for that.  Only trade-off... unfortunately.

**Comment by getdave** [comment]
@DavidRSW Did you ever solve this issue? I'm having the same problem.

**Comment by maximejobin** [comment]
@getdave and @DavidRSW 

Can you paste here your custom headers ? I would like to evaluate what could be done about it.

**Comment by DavidRSW** [comment]
It didn't work, I'm not using it now. But I'll try again!

**Comment by maximejobin** [comment]
Please let me know your config as soon as you can so I can adapt the script! :-)

**Comment by sirbarrence** [comment]
I'm having this problem too. It's unfortunate that nginx add_header works that way - as mentioned in the serverfault link above - but I know that's out of your control.

Should I add an `include my-custom-headers.conf;` line inside every `location` block inside rocket-nginx.conf? Or is there a more proper way that won't cause conflicts when I need to pull down a new version of rocket-nginx.conf?

**Comment by maximejobin** [comment]
I'm working on version 2.0 that will enable you to add custom headers easily.  Stay tuned!

An include or copy/paste could be a temporary solution.

**Comment by maximejobin** [comment]
Fixed in 2.0
