### ISSUE TITLE
Cache Bypass Reason Rocket Cache

### ISSUE THREAD

**Issue by davidmcdougal** [maximejobin/rocket-nginx#25]
Am I missing something, but should this not have hit the nginx cache?
It appears that it is bypassing the cache and just using the standard WP-Rocket cache.

```
X-Rocket-Nginx-Bypass:Yes
X-Rocket-Nginx-File:/var/www/example.com/htdocs/wp-content/cache/wp-rocket/www.example.com///index.html_gzip
X-Rocket-Nginx-Reason:/wp-content/cache/wp-rocket/www.example.com///index.html_gzip
```
I am using EasyEngine and this is my site-available/example.com call of the rocket-nginx files.
```
server {

  # Rocket-Nginx configuration
  include rocket-nginx/rocket-nginx.conf;

    server_name example.com   www.example.com;
```

I am sure I am missing something as to why this is not hitting the cache.

**Comment by maximejobin** [comment]
> X-Rocket-Nginx-Bypass: Did the configuration served the cached file directly (did it bypass WordPress): Yes or No.

It's working totally fine! :-)

**Comment by maximejobin** [comment]
Please check the [Debug section](https://github.com/maximejobin/rocket-nginx#debug) for more information.

**Comment by davidmcdougal** [comment]
Thanks... I was confused by the documentation.

Do you have any tips on using a cdn with your config?  I ask as it seems all cdn rewrites get bypassed when this is active.  Would love to serve my images from a cdn.  I have turned on the cdn option in wp-rocket but still not rewriting image urls.

**Comment by maximejobin** [comment]
Changing the config in the CDN might not be enough (depending on your theme).  You may have to "manually" redo all links.  I do create symbolic links and a new subdomain (cdn) so I don't need a special plugin to transfer all my files.  I also use Cloudflare which is not real CDN.
