### ISSUE TITLE
Mobile Detection Issue

### ISSUE THREAD

**Issue by xemox** [maximejobin/rocket-nginx#28]
Hi Maxime,
I have issue with mobile content, temporarily I have to set $rocket_bypass from 1 to 0, otherwise mobile user will be serve by desktop content.

**Comment by maximejobin** [comment]
The latest version of Rocket-Nginx is not compatible, yet, with the multiple versions handling (desktop, mobile, ...).  I don't have a solution yet to handle what device it is.

That is why the tested version stopped at: 2.6.15.

**Comment by maximejobin** [comment]
Duplicate of #21
