### ISSUE TITLE
Gzip should be applied globally and not only on minified file

### ISSUE THREAD

**Issue by jbma** [maximejobin/rocket-nginx#29]
Hey, 
It should be more effective to apply Gzip and expire on all CSS/JS files in one section directly.
Indeed if you don't enable minification or exclude some files, your CSS/JS won't be into the /min/ folder and gzip won't be applied.

Solution : 
location ~* \.(js|css)$ {
 
	gzip_vary on;
	expires max;
}

**Comment by maximejobin** [comment]
This is a totally valid point.

**Comment by maximejobin** [comment]
It has been added to 1.2 (already pushed to master).
