### ISSUE TITLE
Rocket NGINX fixes Expires: max issues, however, files are still showing "File not cached"

### ISSUE THREAD

**Issue by brianjking** [maximejobin/rocket-nginx#30]
````
HTTP/1.1 304 Not Modified
Server: nginx
Date: Mon, 11 Jul 2016 18:27:20 GMT
Last-Modified: Wed, 06 Jul 2016 21:17:06 GMT
Connection: keep-alive
ETag: "577d7552-162b"
Expires: Thu, 31 Dec 2037 23:55:55 GMT
Cache-Control: max-age=315360000
X-Rocket-Nginx-Bypass: No
X-Rocket-Nginx-Reason: File not cached
X-Rocket-Nginx-File: /home/theupbeatk9/public_html/wp-content/cache/wp-rocket/theupbeatk9.com//wp-content/uploads/2016/06/upbeat-k9-logo.png/index-https.html_gzip
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
````

**Comment by brianjking** [comment]
Currently using:

* NGINX 1.10.1
* PHP 7.0.7
* PHP-FPM
* WordPress 4.5.3
* WP-Rocket 2.8.8

**Comment by maximejobin** [comment]
It seems like this is a request for an image, right ?  If so, images are not cached by Rocket-Nginx so that would be normal.  Rocket-Nginx simply adds headers to make the browser cache them.  As per your headers, it seems like it's working fine:

    Expires: Thu, 31 Dec 2037 23:55:55 GMT
    Cache-Control: max-age=315360000


So yes, Rocket-Nginx that did no cache it.  The browser did though.  It is the right behaviour.

Can you confirm your request's headers is for an image ?

**Comment by brianjking** [comment]
@maximejobin Yes, that was for an image. However, even when I check a CSS or JS file, or any file for that matter it's never showing `X-Rocket-Nginx-Bypass: Yes`

````
HTTP/1.1 304 Not Modified
Server: nginx
Date: Mon, 11 Jul 2016 18:46:01 GMT
Last-Modified: Wed, 06 Jul 2016 21:16:04 GMT
Connection: keep-alive
ETag: "577d7514-ad51"
X-Rocket-Nginx-Bypass: No
X-Rocket-Nginx-Reason: File not cached
X-Rocket-Nginx-File: /home/theupbeatk9/public_html/wp-content/cache/wp-rocket/theupbeatk9.com//wp-content/themes/Divi/js/custom.js?ver=2.7.8/index-https.html_gzip
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
````

**Comment by maximejobin** [comment]
Images, CSS and JS files **are not cached** by Rocket-Nginx.

Only HTML pages (WordPress pages, posts, custom post types) are.

I checked your homepage and it did not trigger Rocket-Nginx to server the file.  My question is: Can you list all the files in the following directory `/home/theupbeatk9/public_html/wp-content/cache/wp-rocket/www.theupbeatk9.com/` ?

**Comment by brianjking** [comment]
@maximejobin 

````
 tree
.
├── 2016
│   └── 07
│       ├── the-upbeat-k9-expanding-to-south-west-florida-as-the-program-launches-in-naples
│       │   ├── index-https.html
│       │   ├── index-https.html_gzip
│       │   ├── index-mobile-https.html
│       │   └── index-mobile-https.html_gzip
│       └── where-do-you-find-your-motivation
│           ├── index-https.html
│           └── index-https.html_gzip
├── blog
│   ├── index-https.html
│   ├── index-https.html_gzip
│   ├── index-mobile-https.html
│   └── index-mobile-https.html_gzip
├── category
│   ├── general
│   │   ├── index-https.html
│   │   └── index-https.html_gzip
│   └── press-release
│       ├── index-https.html
│       └── index-https.html_gzip
├── contact-us
│   ├── index-https.html
│   ├── index-https.html_gzip
│   ├── index-mobile-https.html
│   └── index-mobile-https.html_gzip
├── index-https.html
├── index-https.html_gzip
└── locations
    ├── boston-massachusetts
    │   ├── index-mobile-https.html
    │   └── index-mobile-https.html_gzip
    ├── index-https.html
    ├── index-https.html_gzip
    ├── index-mobile-https.html
    ├── index-mobile-https.html_gzip
    └── naples-florida
        ├── index-mobile-https.html
        └── index-mobile-https.html_gzip

12 directories, 28 files
````

**Comment by maximejobin** [comment]
Did you alter the script in any way ? (even a suggestion made by the WP-Rocket team... like commenting a line or anything else.)

**Comment by maximejobin** [comment]
Because I think you checked the "mobile" cache in WP-Rocket.  So, if you did that, maybe you also edited the script as suggested by them to get around a bug with mobile cache in Rocket-Nginx.

**Comment by brianjking** [comment]
I did enable the mobile cache in WP-Rocket and as per http://docs.wp-rocket.me/article/663-mobile-cache-desktop-view-displayed-for-mobile-devices I made the change to line 23.

https://github.com/maximejobin/rocket-nginx/blob/master/rocket-nginx.conf#L23

I've now removed that change and set it back to 1.

Please advise, thanks.

**Comment by maximejobin** [comment]
2 things here:

1) By commenting the line, you'll never see the "Yes" you are looking for.
2) By NOT commenting the line, you won't get the cache working for both mobile AND desktop.

The reason is that Rocket-Nginx cannot detect correctly if it's a mobile or not.  I am working on a fix for that.

If your site is reponsive (which looks like it is), you do not need to activate the "mobile cache".  Please check if the website looks the same with and without the option checked.  If it is the same, don't check this checkbox and you'll get the "Yes" for the Bypass.

**Comment by brianjking** [comment]
Inside of WP-Rocket are you referring to the option Enable caching for mobile devices or Create a caching file for mobile visitors?

Currently I have the following set in WP-Rocket:

- [x] Enable caching for mobile devices.

- [ ] Create a caching file for mobile visitors.

Line 23 is set to `1` in `rocket-nginx.conf`

**Comment by maximejobin** [comment]
Ok, that way, you are good.  Simply leave the rocket-nginx.conf as is (without commenting a line) and you should get a "Yes".

**Comment by maximejobin** [comment]
I checked your homepage and I confirm.... it works! :smiley:

**Comment by brianjking** [comment]
Thanks @maximejobin
