### ISSUE TITLE
"server" directive is not allowed here

### ISSUE THREAD

**Issue by howtofixthings** [maximejobin/rocket-nginx#34]
Hi!
Could someone please explain this part to me? Idk what to do...

My sites are under: /etc/nginx-sp/vhosts.d/
and for each site i have domain.conf and domain.d
and under each domain.d i have one file called main.conf

and my installation is under /etc/nginx-sp/rocket-config
including the file rocket-nginx (without any extension name)

But idk what to do next :S

**Edit:** Ive come a bit on the way, but now i get this error:
 **"server" directive is not allowed here in /etc/nginx-sp/vhosts.d/domain.d/main.conf:1**

```
Then, in your configuration file, you must include the configuration. If your websites configurations are in /etc/nginx/sites-available, you need to alter your configuration:

server {
  ...

  # Rocket-Nginx configuration
  include rocket-nginx/rocket-nginx.conf;

  ...
}

> 
```

**Comment by maximejobin** [comment]
In your `server { ... }` section, you must simply add this:

    # Rocket-Nginx configuration
    include rocket-nginx/rocket-nginx.conf;

**Comment by howtofixthings** [comment]
Got it thx. Saw that i needed to rename the conf file with serverpilot and then to add the line not the whole server thing :)

**Comment by Dibbyo456** [comment]
@howtofixthings So, are you using it ServerPilot? Works fine?

**Comment by maximejobin** [comment]
It can work on ServerPilot without any problem.
