### ISSUE TITLE
Cron job  - Parse error: syntax error, unexpected '*', expecting end of file

### ISSUE THREAD

**Issue by howtofixthings** [maximejobin/rocket-nginx#35]
Hey, none of the alternatives works for me, get the same error every time

Parse error: syntax error, unexpected '*', expecting end of file

```
Then, manually a cron job every 15 minutes (it should be enough for most websites):

*/15 * * * * wget -q -O - http://www.website.com/wp-cron.php?doing_wp_cron >/dev/null 2>&1

or

*/15 * * * * curl http://www.website.com/wp-cron.php?doing_wp_cron > /dev/null 2>&1

or

*/15 * * * * cd /home/user/public_html; php wp-cron.php > /dev/null 2>&1

Make sure you test that your tasks still run after this change!`
```

**Comment by maximejobin** [comment]
It looks like you pasted this into a PHP file.

I suggest you Google "How to add a crontab" depending on your configuration.  When in SSH, you can simply run:

`crontab -e`

... and paste ONE of the line.  Make sure you change the URL.

**Comment by howtofixthings** [comment]
ok got it, thought i needed to add it to wp-config.php under define('DISABLE_WP_CRON', true); 
thx for the quick support!

does it matter if i use www or non-www in the url? 
(my website always redirect to non-www)

**Comment by maximejobin** [comment]
Good!
No, it does not matter how your URL is structured! :-)
