### ISSUE TITLE
Purging CSS file

### ISSUE THREAD

**Issue by theroyist** [maximejobin/rocket-nginx#36]
I am looking for a way to purge a CSS stylesheet but I can't figure it out. 

I think it's stalled on the NGINX cache. Moreover, I can't seem to find where the NGINX cache folder is. 

I have also been following this discussion with no results. 

http://stackoverflow.com/questions/6236078/how-to-clear-the-cache-of-nginx

**Comment by maximejobin** [comment]
If you simply flush the cache from WP-Rocket plugin, it will generate new CSS files with different names. This will be "the same" as flushing the cache.

**Comment by theroyist** [comment]
I see.. I had excluded this file from being minified by WP-Rocket, so I will try your suggestion. thanks

**Comment by theroyist** [comment]
ok it works now, but only if I Enable caching for logged in users !

**Comment by maximejobin** [comment]
Is it a file you are enqueueing yourself and that you update often ?

If so, I suggest you enqueue it so it adds something at the end like: "..../style.css?2016-09-21"

That way, you simply change the date when you update it and the cache won't be valid.

**Comment by maximejobin** [comment]
You should not alter your theme's CSS file as you'll lose data when an update occurs.

If you enqueue your own CSS file, see this page:
https://developer.wordpress.org/reference/functions/wp_enqueue_style/

The important parameter to fill is the `$ver`.

**Comment by theroyist** [comment]
no this style.css is in my child folder. However the theme adds this version number at the end: ?ver=4.6.2

**Comment by theroyist** [comment]
ok, so now the process doesn't work again. 

1. I make a change to https://www.domain.con/wp-content/themes/x-child/style.css
2. I clear WP-Rocket cache
3. Inside the newly generated cache files, the changes are not reflected

This is confusing..

**Comment by maximejobin** [comment]
Please post the enqueueing code from your child's functions.php file.

**Comment by theroyist** [comment]
```
   if ( is_child_theme() ) {
      $dep = ( apply_filters( 'x_enqueue_parent_stylesheet', false ) ) ? array( 'x-stack' ) : NULL;
      wp_enqueue_style( 'x-child', get_stylesheet_directory_uri() . '/style.css', $dep, X_VERSION, 'all' );
    } else {
      wp_enqueue_style( 'x-stack' );
    }
```

**Comment by maximejobin** [comment]
You need to change the `X_VERSION`.

I would change it for something like this (note that I did not fully test that code):

    if ( is_child_theme() ) {
      $dep = ( apply_filters( 'x_enqueue_parent_stylesheet', false ) ) ? array( 'x-stack' ) : NULL;
      $last_modified_time = filemtime( get_stylesheet_directory() . '/style.css' )
      wp_enqueue_style( 'x-child', get_stylesheet_directory_uri() . '/style.css', $dep, $last_modified_time, 'all' );
     } else {
      wp_enqueue_style( 'x-stack' );
     }

**Comment by theroyist** [comment]
ok now it works but I have to disable caching for logged in users :) thanks!

**Comment by maximejobin** [comment]
I don't get why you "have" to. The provided could should make it work both ways.

**Comment by theroyist** [comment]
Yes what i mean is:

Enable caching for logged in users: I have to clear WP-Rocket dache to see changes

Disable caching for logged in users: I can see changes instantly when browser refreshes

**Comment by maximejobin** [comment]
That's perfect!  You can now enjoy the caching and update your CSS at will! :-)
