### ISSUE TITLE
CORS header ‘Access-Control-Allow-Origin’ missing).

### ISSUE THREAD

**Issue by theroyist** [maximejobin/rocket-nginx#37]
Hi,

Does your config overwrite any header rules I have setup in my original configuration?

I have set inside: etc/nginx/sites-enabled/default
```

location ~ .(ttf|ttc|otf|eot|woff|woff2|font.css|css|js)$ {
add_header Access-Control-Allow-Origin "*";
}
```

I am receiving this error:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://example.cloudfront.net/fonts/didot-24b-webfont.woff2. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Also when doing curl -I 

I cannot see the access-control-allow-origin header... I only see X-rocket headers..

many thanks

**Comment by theroyist** [comment]
This is a related discussion which could entail an issue with rocket-nginx:

http://stackoverflow.com/questions/18450310/nginx-add-header-not-working

**Comment by theroyist** [comment]
sorry I fixed the issue, nothing to do with WP-Rocket. 

I had defined locations for fonts twice and only the first instance was being processed by Nginx.

**Comment by maximejobin** [comment]
You'll have to add your headers to Rocket-Nginx configuration. This is because of the way Nginx is built.

I am working on a config generator... but it's not done yet. :-)

**Comment by theroyist** [comment]
I tested that, and it's not necessary. I have fixed the issue by adding this in my original config:

 location ~ \.(ttf|ttc|otf|eot|woff|woff2|font.css|css|svg|svgz)$ {
        add_header Access-Control-Allow-Origin "*";
        log_not_found off;
        access_log off;
        expires max;
    }

Also need to make sure you define properly MIME types. I am surprised no-one else mentioned any problems with web-fonts. It took me a lot of time to figure it out..
