### ISSUE TITLE
Purging Nginx Files

### ISSUE THREAD

**Issue by theroyist** [maximejobin/rocket-nginx#39]
Hi,

Could you please tell me where nginx stores cached files?

It appears that even if I clear the WP-Rocket cache several times, nginx still stores older versions?

many thanks

**Comment by maximejobin** [comment]
Nginx stores cached files in memory.  There is no way to purge files.

If it looks like you have a caching problem, make sure you disable the cache correctly.  Also, check the HTTP headers to validate.  Finally, you can also, if you use Chrome, select "Disable cache" from the Inspector to make sure your browser serves a fresh copy of the page (or media).
