### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by mihdan** [maximejobin/rocket-nginx#4]
How to send headers Last-Modified and Not Modified in you rocket config?

**Comment by maximejobin** [comment]
Rocket-Nginx already takes care of these headers with the `expires` directive.  The returned value depends on when the cached file was generated.

You do not have to alter the configuration to do so. When you purge your cache, Nginx will detect that the file is not the same and update its values accordingly.

**Comment by mihdan** [comment]
I use this configuration file https://github.com/maximejobin/rocket-nginx

**Comment by maximejobin** [comment]
The configuration already takes care of Last-Modified and Not Modified.

You have nothing to add or edit.
