### ISSUE TITLE
Checking for user-defined cookies

### ISSUE THREAD

**Issue by junaidbhura** [maximejobin/rocket-nginx#40]
Hi there,

I'm trying to set a cookie under "Advanced Settings" -> "Don't cache pages that use the following cookies" . But it looks like this configuration does not take that into account, and the pages are cached nonetheless.

Is there a way to fix this?

**Comment by maximejobin** [comment]
Unfortunately, the script cannot be dynamic and adjust the configuration by entering new values like you are doing.

You will have to alter the cookie management section and add your cookies there (cookie1|cookie2|...) at [line 98](https://github.com/maximejobin/rocket-nginx/blob/master/rocket-nginx.conf#L98) of the Rocket-Nginx configuration.

If a contributor would help with issue #38, what you are asking could be automated in a generation script.

**Comment by junaidbhura** [comment]
Hmm, I figured there would be no way. But changing this config file could cause conflicts with future updates from this repository.

Maybe there's a more elegant solution? Maybe including an external file in the config which is added to this repository's .gitignore which has a list of all cookies?

Not sure if that would be the best way to do it, just a suggestion!

**Comment by maximejobin** [comment]
Of course, editing the configuration manually is not the best option in the long run.  But it's an option for now.

When the configuration generator will be completed, it will be easier to make these kinds of modifications.

**Comment by maximejobin** [comment]
Fixed in 2.0
