### ISSUE TITLE
Multiple Slashes - Nginx Not Cached

### ISSUE THREAD

**Issue by theroyist** [maximejobin/rocket-nginx#42]
I have enabled debug mode and for some reason files are not cached in Nginx and I can see in debug headers multiple slashes //.. why is this happening ?

x-rocket-nginx-bypass	Yes
x-rocket-nginx-file	/var/www/html/wp-content/cache/wp-rocket/www.domain.com///index-https.html_gzip
x-rocket-nginx-reason	/wp-content/cache/wp-rocket/www.domain.com///index-https.html_gzip

**Comment by maximejobin** [comment]
As for multiple slashes, you can see issue #13 for an explanation.

Files are cached and the "Yes" confirms it. "Yes" means: "Yes, we bypassed WordPress and served the cached file". :-)

**Comment by theroyist** [comment]
ok so this is not a problem at all then :)

**Comment by maximejobin** [comment]
Absolutely not!

**Comment by theroyist** [comment]
perhaps for future the naming convention could be changed - to me it reads: "was nginx bypassed? " - " Yes"

**Comment by maximejobin** [comment]
What the script is doing is trying to "bypass" PHP by serving static files.

That said, I understand it can be confusing. Maybe "Serving static file" would be less confusing.

**Comment by theroyist** [comment]
Yes even better "Serving Nginx Static File"
