### ISSUE TITLE
Beware: GZIP + Brotli

### ISSUE THREAD

**Issue by goaround** [maximejobin/rocket-nginx#48]
Some client (Google Search Console + Google Crawler probably) have problems decoding with Brotli compressed gzip-files. If Brotli is active on the server.

At the moment the rocket-nginx.conf just checks if the client accept gzip and than serves the _gzip-file which will compressed again with Brotli:
`# Is GZIP accepted by client ?`
`if ($http_accept_encoding ~ gzip) {`
`set $rocket_encryption "_gzip";`
`}`

For this reason I check if the client accept Brotli and unset $rocket_encryption:
`# Is Brotli accepted by client ?`
`if ($http_accept_encoding ~ br) {`
`set $rocket_encryption "";`
`}`

**Comment by maximejobin** [comment]
Do you know what is the priority order and how it's set when both gzip and Brotli are active?

Thank you for letting me know.

**Comment by goaround** [comment]
Nginx takes the gzip-file and compresses it again with Brotli on the fly.
That works with modern browsers nevertheless but some google tools and I guess the google bot, too have problems with it.

**Comment by maximejobin** [comment]
My understanding was that it was an alternative to GZIP.  Not that it used the GZIP file and used Brotli after it.  I did not see that in the documentation.  

Can you educate me on your sources?  That way, I can code it properly.

**Comment by goaround** [comment]
It is an alternative to GZIP.
I think the problem is, rocket-nginx serves the gzip-file and Nginx don't know that the the file is gzip-compressed and compresses it again with Brotli.

With `$http_accept_encoding ~ gzip` you only check if the client accept `gzip` but it can accept `br`, too.

I let Google render a few pages without the check if the client accept `br `:
![42rer 1](https://cloud.githubusercontent.com/assets/5927337/23863794/f62fa0b0-0810-11e7-97a5-cdde805478b8.png)
He took the gzip-file and the "Content-Encoding" says br
![0hcyu](https://cloud.githubusercontent.com/assets/5927337/23863561/6b8a2b4c-0810-11e7-85b4-bac264dac9f3.png)

**Comment by maximejobin** [comment]
Ok, I get what you mean.

My main concern now is: when GZIP and BR are acceptable encoding, how do I ask Nginx (via the configuration file I made) what is the encoding that it will use ?  Then, if it's "BR", the code suggestion you did make sense.  If it's GZIP, we can use the code as is.

The question remains: when both are available, how can I know which one did Nginx pick ?

This is what I need to figure.

**Comment by goaround** [comment]
I think if Brotli is active and the client accept it, it will take brotli.

**Comment by maximejobin** [comment]
I understand. Now, I need a confirmation of that behaviour. :-)
