### ISSUE TITLE
No Gzip and X-Rocket-Nginx-Bypass to No for all ressources

### ISSUE THREAD

**Issue by fadupla** [maximejobin/rocket-nginx#49]
Hi @maximejobin ,

Thanks you first of all for your work !
I saw you were currently working when you can on the version 2 but I encounter an issue with the current version and I wonder if you could help me to figure out why I can't have the ressources of any WordPress with WP Rocket gziped.
For example on this WordPress website we made : http://melvi2017.com/
"X-Rocket-Nginx-Bypass" header is set to No for every ressources and the response header doesn't have the "Content-Encoding:gzip" indication.

- gzip is [well enabled](https://checkgzipcompression.com/?url=http%3A%2F%2Fmelvi2017.com%2F) on the server 
- the configuration file is in place as we have the header "X-Rocket-Nginx-Bypass" visible
- the hosting is managed with plesk

Do you have any ideas or solution for this ?

Many thanks,

--
Fabien

**Comment by maximejobin** [comment]
If you activate the [debug options](https://github.com/maximejobin/rocket-nginx#debug), you'll get the reason why you did not bypass PHP.

With that information, I will be able to help.

I also suggest you check issue #18 about how to configure the script with Plesk.

**Comment by fadupla** [comment]
Voilà, it is activated.

I now see in example : 

http://melvi2017.com/wp-content/cache/min/1/a12d50d821547bc0edd9c1acd6282f93.css

`X-Rocket-Nginx-Bypass:No
X-Rocket-Nginx-File:/var/www/vhosts/melvi2017.com/httpdocs/wp-content/cache/wp-rocket/melvi2017.com//wp-content/cache/min/1/a12d50d821547bc0edd9c1acd6282f93.css/index.html_gzip
X-Rocket-Nginx-Reason:File not cached`

It seems to be the file path that is wrong...
How may I correct that ? (didn't find any clues in issue #18 )

Thanks @maximejobin

**Comment by maximejobin** [comment]
Did you edit the script?  Because it is looking for a HTML file instead of a CSS file.  

That is the problem you are having.

**Comment by fadupla** [comment]
Nop, the script is not edited, the only difference is the "set $rocket_debug 1;"

**Comment by fadupla** [comment]
The correct path file should be

`/var/www/vhosts/melvi2017.com/httpdocs/wp-content/cache/min/1/a12d50d821547bc0edd9c1acd6282f93.css`

for the cached file http://melvi2017.com/wp-content/cache/min/1/a12d50d821547bc0edd9c1acd6282f93.css
but the rocket-nginx.conf script looks for 

`/var/www/vhosts/melvi2017.com/httpdocs/wp-content/cache/wp-rocket/melvi2017.com//wp-content/cache/min/1/a12d50d821547bc0edd9c1acd6282f93.css/index.html_gzip`

I don't understand why there is "index.html_gzip" in the path of this css file and why there is a mix between the "wp-content/cache/min" and the "cache/wp-rocket/melvi2017.com" folders.

Could it be a problem with "rocket_wpcontent_directory " in your script that I should change or anything else ?
Sorry to bother you with that, I feel like close to the solution but still missing what is wrong...

 Thank you in advance.

**Comment by fadupla** [comment]
Bonjour @maximejobin 
We didn't succeed to get proper link to the cached ressources yet.
If you have any idea or solution, we are all hears open... thanks !

**Comment by maximejobin** [comment]
The CSS rule in the configuration should be used for the CSS file.  I don't understand why it's trying to add the `/index.html_gzip`.  There is something in your original configuration that might overwrite what the Rocket-Nginx configuration is doing.

**Comment by maximejobin** [comment]
Can you post all your Nginx configuration files?

**Comment by fadupla** [comment]
The nginx.conf file : https://gist.github.com/fadupla/05480bcab4c347ce033fe1a14428896d
Ths rocket-nginx.conf file : https://gist.github.com/fadupla/8dab92190d15992ca355b2ca2e15f6f6
The directives added in the vhost in Plesk : 

```
# Directives supplémentaires Nginx dans Plesk
# Rocket-Nginx configuration
include rocket-nginx/rocket-nginx.conf;
```

Thanks

**Comment by maximejobin** [comment]
Your configuration looks good.  I have not seen that kind of behaviour yet.  That is a first...

**Comment by fadupla** [comment]
So frustrating 😢 
If you have any idea popping out your mind, or when I can test the v2 of your configuration file please let me know !
Thanks

**Comment by eddydu44** [comment]
I don't understand where is the php location directives in your nginx.conf
Si tu es français je peux t'expliquer en fr ^^ 
Moi j'avais un problème similaire avec mon site, il disait toujours bypass, bypass,.....
Mais j'ai trouvé la solution, il faut mettre la directive 
`include rocket-nginx/rocket-nginx.conf;`
Dans la partie 'location ~ (\.php)' et surtout pas ailleurs
chez moi mon fichier de configuration du site ressemble à ça 
`location ~ (\.php) {
			include rocket-nginx/rocket-nginx.conf;
			include fastcgi.conf;
			fastcgi_pass php;
}`
Et ça a marché pour moi ! 👍 
In English:
I already faced to this issue in the past. For me the solution was very simple : i simply moved the directive 
`include rocket-nginx/rocket-nginx.conf;`
Inside the php location : `location ~ (\.php)` and not before or anywhere else.

**Comment by fadupla** [comment]
Salut @eddydu44 merci pour ton message. Comment je peux trouver où la mettre exactement ? Là j'ai mis "include rocket-nginx/rocket-nginx.conf;" dans plesk dans les "Directives supplémentaires Nginx". Tu parles de "php location directives" mais je ne trouve pas où elle est ? Merci !

**Comment by eddydu44** [comment]
Je n'est jamais utilise plesk... Mais je pense que ca doit etre dans un autre fichier de configuration. Tu n as pas accès aux fichiers de ton serveur en fait ? 
Moi par exemple j'ai include fastcgi.conf; dans lequel on pourrait aussi mettre la directive include rocket-nginx/rocket-nginx.conf;
Je pense que si tu trouves un fichier de conf de php ca fera l'affaire.

**Comment by fadupla** [comment]
@eddydu44 si si j'ai accès à tout.
Je vais chercher, merci

**Comment by kevin25** [comment]
I have the same issue. All static files weren't cached and served.

**Comment by fadupla** [comment]
hello @kevin25 I am interested if you find any solution... because I didn't

**Comment by kevin25** [comment]
I'm checking it. We haven't heard anything from you @maximejobin

**Comment by maximejobin** [comment]
The problem seems to be linked with your Plesk configuration. I'd really like to help but I have no free time to investigate such problem. If you want to hire me to debug it, I'll gladly do it. Just email me and we'll make it work.

**Comment by mascu** [comment]
Hello,

Did someone found a solution for Plesk?

All my paths are like this "/var/www/vhosts/my-domain/httpdocs/wp-content/cache/wp-rocket/my-domain//wp-content/cache/min/1/84f9b569995d819e5ea7de76c10eee71.css/index-https.html_gzip"

Put "include" in "location ~ (\.php)" doesn't change anything.

Thank you!

**Comment by penguinmaid44** [comment]
This problem exists on Ubutu 16.04 also - it has nothing to do with plesk - crappy support - thanks for nothing.  A$*%#

**Comment by penguinmaid44** [comment]
Oh yeah - tried it on multiple severs -

**Comment by maximejobin** [comment]
@penguinmaid44 You have a server running Ubuntu and Nginx without any control panel ? If that's the case, I'd like to access it.

What do you mean "crappy support" ? About what support are you talking about ?

**Comment by french50** [comment]
Has anyone finally found the problem?

I have exactly the same case (and it's not at all for a Plex server)

**Comment by cat1510** [comment]
I have the same problem.

No Plex Server. Just:
Ubuntu 16.04 LTS
Nginx 1.14
WP - Rocket 3.3

for example: 

server: nginx/1.14.2
status: 200
x-rocket-nginx-file: /var/www/performance.websiteprofis.de/web/wp-content/cache/wp-rocket/performance.websiteprofis.de//wp-content/plugins/header-footer-elementor/assets/css/header-footer-elementor.css?ver=1.1.2/index-https.html
x-rocket-nginx-reason: File not cached
x-rocket-nginx-serving-static: No

Or should I ask WP - Rocket Support?

**Comment by LuisUrrutia** [comment]
Same problem! I don't know what to do

**Comment by yqchilde** [comment]
I have the same problem, but my site is https, but the end of the file is / index.html,. The correct one is index-https.html_gzip,. I haven't changed the code and pulled the latest code.
