### ISSUE TITLE
When GZIP (.html_gzip) is enabled all html request is interpreted as downloads

### ISSUE THREAD

**Issue by djaevlen** [maximejobin/rocket-nginx#50]
Hi there and thanks for this awesome conf!

I think I have the same problem as this closed issue (https://github.com/maximejobin/rocket-nginx/issues/45). Im using a custom path to the /cache folder. More exactly `/app/cache/wp-rocket/www.example.com`. When I enable the conf to read the `.html_gzip` file from the /cache folder it interpretes it as an download. And when I remove the _gzip it works fine.

Im using Roots.io's Trellis and Bedrock setup. I thinking it has something to do with the nginx server setup not being able to pick up `.html_gzip` as an valid format. 

I just wanted to know if you have any input on this, before I throw it over to the guys at roots.io. 

The nginx conf is found here: [nginx.conf](https://github.com/roots/trellis/blob/master/roles/nginx/templates/nginx.conf.j2)
The WordPress conf is found here: [wordpress-site.conf](https://github.com/roots/trellis/blob/master/roles/wordpress-setup/templates/wordpress-site.conf.j2)

**Comment by maximejobin** [comment]
Version 2.0 of the script will take care of the different wp-content folder option.

Can you post the edit you did?  You probably think you did it right but maybe you missed something.

**Comment by djaevlen** [comment]
This is the conf i use. I have edited line 24 and 27 with /app instead of /wp-content. 

https://gist.github.com/djaevlen/3e2859421c7952f54767c708ed605287

When I empty the string at line 49 it works. But if I let the string be "_gzip" it fails.

**Comment by djaevlen** [comment]
Any news on this before I throw it over to roots.io?

**Comment by maximejobin** [comment]
I don't think the problem has anything to do with roots.io.

The problem comes from the Nginx configuration.  It might be your Nginx configuration or Rocket-Nginx.  It would need investigation.

**Comment by sdmpxs** [comment]
I realise this was a few weeks ago now but I've just had the same issue. I needed to edit lines 132 & 145 too as they reference wp-content and not my custom content directory name. Updated those and it is working perfectly. 

Thanks!

**Comment by maximejobin** [comment]
Great!  I'm about to push out version 2.0.  It's done and just need validation. It's gonna solve everything right off the bat.  Stay tuned!

**Comment by eddydu44** [comment]
I'm impatient to use this new version. Please upload it ! ☺️

**Comment by djaevlen** [comment]
Nice to hear! Looking forward to version 2.0 ☺️

**Comment by maximejobin** [comment]
Version 2.0 was released yesterday night.

**Comment by sdmpxs** [comment]
Is there a need to upgrade to 2.0 if 1.2 is working fine? What is the main difference?

**Comment by maximejobin** [comment]
There is no "need" to upgrade if it's working fine.  That said, there are some bug fixes and nice enhancements.

You can get more information here:
https://github.com/maximejobin/rocket-nginx/releases/tag/2.0

To update to the latest version, you need to:
1) `git pull`
2) Rename `rocket-nginx.ini.disabled` to `rocket-nginx.ini` ( `mv rocket-nginx.ini.disabled rocket-nginx.ini`)
3) Run the PHP parser: `php rocket-parser.php`
4) Change your include file from `include rocket-nginx/rocket-nginx.conf` to `include rocket-nginx/default.conf`
5) Test if the configuration works: `nginx -t`
6) Reload the Nginx configuration: `service nginx reload`

To me, that is a 5 minutes well invested to be up-to-date, fix some bugs and be ready for more improvements in the future!

In the end, it is your call! :-)

**Comment by djaevlen** [comment]
Since 2.0 has launched im closing this.

**Comment by BigWhale** [comment]
I have 2.0.1 version of the config and I am also seeing this. However, it happens very very rarely and I am having trouble locating the source of the error. I wonder if anyone else is having this problem.

**Comment by maximejobin** [comment]
@BigWhale If you can provide an example and we can reproduce it, it will be fixed.

**Comment by BigWhale** [comment]
I wish I was able to locate the problem. At rare times gzipped content is served to the client and client downloads it. I was then able to gunzip the file in question and I was left with on-gzipped page content.

My guess would be that for some reason nginx compresses already compressed file.

**Comment by maximejobin** [comment]
My guess is that it might be because of Brotli's compression. Did you update to the last version of Rocket-Nginx ? Then regenerate your config files. Let me know if you still have this problem.

**Comment by gelaxe** [comment]
This issue appears on several mobile devices like iPhone 5, ios10.

**Comment by maximejobin** [comment]
@gelaxe 
What version of Rocket-Nginx are you using ?
I'm pretty confident it was caused by Brotli not being handled and was fixed in the latest version. If you have a new case to submit, feel free to send a private message if you don't want to share everything publicly.

I will need more information about your configuration and the URL to reproduce and fix it.
