### ISSUE TITLE
Can not generate default.conf

### ISSUE THREAD

**Issue by hellhydra** [maximejobin/rocket-nginx#52]
I run cmd "rocket-parser.php" but it do nothing.
Please help

**Comment by maximejobin** [comment]
Did you follow the [instructions](https://github.com/maximejobin/rocket-nginx#installation) ?

You first have to rename the ini file:

    cp rocket-nginx.ini.disabled rocket-nginx.ini

Then run the parser:

    php rocket-parser.php

**Comment by hellhydra** [comment]
Yes I did.
![err1](https://cloud.githubusercontent.com/assets/20238524/25705194/b01fa006-3106-11e7-8e6d-84c6b46a3fee.jpg)

**Comment by maximejobin** [comment]
Can you run :

    php rocket-parser.php

... and show me the result ?

**Comment by hellhydra** [comment]
![err2](https://cloud.githubusercontent.com/assets/20238524/25706029/76a89b4a-3109-11e7-9ebd-db006da6ec44.jpg)

**Comment by maximejobin** [comment]
Can you do:

    ls -l

... and show the result ? Are files empty ?

**Comment by hellhydra** [comment]
![err3](https://cloud.githubusercontent.com/assets/20238524/25710044/3e722e4c-3115-11e7-9cf4-243db6c09c6a.jpg)

**Comment by maximejobin** [comment]
That is really weird. Is there a way I could connect to this server and check it out ? I'd like to help you on this one. You can email me the info: m @ ximejobin [.dot.] com

**Comment by deathbat6661** [comment]
I have the same problem here, on Ubuntu 14 and nginx version 1.13.0

![rocket](https://cloud.githubusercontent.com/assets/4346175/25962315/649b6844-36a7-11e7-8916-88b9589ddcbf.png)

**Comment by maximejobin** [comment]
I just pushed version 2.0.1 where I use a different approach to write the files.  Can you pull the new version, try it and report the results here ?

**Comment by deathbat6661** [comment]
Still same, no .conf is generated

http://s15.postimg.org/cryfjdtxn/screenshot_43.png

**Comment by maximejobin** [comment]
If someone can create an ssh access for me and send it to me via email : m @ ximejobin . com

I will gladly debug it to see what the problem is. I also use Ubuntu 14 and did not get any problems.

**Comment by maximejobin** [comment]
@deathbat6661 Your problem is solved. You did not install the script correctly.

@hellhydra Let me know if the update fixed your problem.
