### ISSUE TITLE
Replace if to map - https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/

### ISSUE THREAD

**Issue by dmitry-yackevich** [maximejobin/rocket-nginx#53]
Nginx generate separate in-memory config for each if statement, so it's hell to debug it.
https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/

Map is more convenient way for conditions. For example, you can replace 
`if ($http_accept_encoding ~ gzip) {
	set $rocket_encryption "_gzip";
}`
to
`map $http_accept_encoding $rocket_encryption {
        default   "";
        ~gzip     "_gzip";
}
`

http://nginx.org/en/docs/http/ngx_http_map_module.html

**Comment by maximejobin** [comment]
I will definitely take a look at that. Thank you for letting me know how to improve the script! :-)

**Comment by maximejobin** [comment]
After further investigation, `map` only works at `http` level. That is why it can't be used. Rocket-Nginx is included at the `server` level.

I agree that `if` is evil... in certain cases. In our case, they simply cannot be replaced by `map`.

Thank you for taking the time to read the code. Do not hesitate if you have other suggestions!
