### ISSUE TITLE
YITH Wishlist count incorrect when rocket-nginx is enabled

### ISSUE THREAD

**Issue by chancarlo** [maximejobin/rocket-nginx#56]
Hi Maxime, first of all thanks for sharing your great work. I'm using it on my site at the moment. However I have some issues with YITH Wishlist plugin. For example when I have items on my wishlist, it displays the count similar to WooCommerce cart. Whenever I navigate between pages, the count changes or disappears. There are instances also when the wishlist page itself does not display the correct items until you delete an item, then it refreshes with the correct list.

I tried changing WP rocket settings and even server SSL settings until finally I was able to isolate the issue to be caused by rocket-nginx. When I exclude it from server settings, then it wishlist works. Any chance you could have a look at this?

**Comment by maximejobin** [comment]
I suspect that the count is not called with Javascript. Therefore, once the page is in cache, it displays the same information for all visitors.

I don't know this plugin.

**Comment by chancarlo** [comment]
Thanks for replying. For different visitors, they get different counts so it's working between different visitors. The only issue is for the same user, browsing between different pages of the site with common header, the wishlist count does not update on some pages. Anyway, probably not related to your script.

I tried adding this to the rocket-nginx.ini
      cookie_invalidate[] =  "yith_wcwl_products"

before executing php rocket-parser.php and so far I think it does the trick. I haven't tested it that much but looks like it worked for my limited tests.

**Comment by maximejobin** [comment]
Good to know adding the cookie seemed to make it work. I will leave the ticket open a couple of weeks and would expect a new comment from you saying if it solved the problem or not. If I don't hear back from you, I'll assume everything is running fine.

Thank you for the update.
