### ISSUE TITLE
Problem with subsite

### ISSUE THREAD

**Issue by flschaves** [maximejobin/rocket-nginx#57]
Hi Maxime, first of wall thanks for this great module.
Just wanna know if it's possible this module work with subsite, for example:
My main site root is /var/www/example.com/htdocs/ and all works perfeclty.
But for the blog: /var/www/example.com/htdocs**/blog/**, the $rocket_file is looking for /var/www/example.com/htdocs/wp-content/cache/wp-rocket/www.example.com//blog//index-https.html_gzip ;(

Is there any way to make it work?

**Comment by maximejobin** [comment]
What does your nginx configuration file looks like ?  Do you only have one configuration file for the main site and all subsites? Or if you have multiple configurations ?

**Comment by flschaves** [comment]
I've installed this site with EasyEngine, here is the file configuration:
`server {
        listen 80;
        listen [::]:80;

        server_name www.example.com example.com wpexpert.com.br;
        return 301 https://www.example.com$request_uri;
}

server {

    server_name example.com   www.example.com;


    access_log /var/log/nginx/example.com.access.log rt_cache;
    error_log /var/log/nginx/example.com.error.log;


    root /var/www/example.com/htdocs;



    index index.php index.html index.htm;


    include common/php7.conf;

    include common/wpcommon-php7.conf;
    include common/locations-php7.conf;
    include /var/www/example.com/conf/nginx/*.conf;

    # Rocket-Nginx configuration
    include rocket-nginx/default.conf;
}`

And for the blog works, aditional location on another file included before:
`location /blog/ {
    index index.php index.html index.htm;
    try_files $uri $uri/ /blog/index.php?q=$uri&$args;
}`

**Comment by maximejobin** [comment]
Ok, so it's really a "subsite" and not a multisite.

The quickest answer would be: why not use a multisite ? That way it would work with Rocket-Nginx.

If you can, that is the best thing to do. If you can't, Rocket-Nginx cannot do it "as is".

**Comment by flschaves** [comment]
Really, I have not thought of this before, but is the best thing.
Thansk a lot Maxime!
