### ISSUE TITLE
Fastcgi (with latest nginx) is serving mobile cache to users on Desktop

### ISSUE THREAD

**Issue by beeriz** [maximejobin/rocket-nginx#58]
Hey, 
Any idea how to prevent nginx from serving cached mobile pages to users on Desktop?
I'm using WP Rocket with this configuration

Thank you

**Comment by maximejobin** [comment]
The configuration should not serve mobile pages to desktop users.

WP-Rocket gives you the option to have your pages being responsive or save one version for desktop and one version for mobile.

Please be more specific and give a real use case so it can be validated.

**Comment by AminulBD** [comment]
@maximejobin Sometimes we need to use separate theme for WordPress and this is important to store mobile cache as different version.  I know it's difficult to check each request is mobile or not but possible this will great.

**Comment by maximejobin** [comment]
It is not possible to detect if it is a mobile or desktop device from Rocket-Nginx. I tried to do it but there are so many validations to do that it made every request slower. More than that, there was no way I could do all validations because NGINX's configuration "coding" is not a real langugage.

**Comment by bdtech** [comment]
This should work for a majority of cases, append the $is_mobile var to the cache key.

### Map Mobile
map $http_user_agent $is_mobile {
    default 0;
    ~*android|ip(hone|od)|windows\s+(?:ce|phone) 1;
    ~*symbian|sonyericsson|samsung|lg|blackberry 1;
    ~*mobile 1;
}

**Comment by maximejobin** [comment]
The reason I did not do it is basically because it's incomplete. By doing that, I know people will create tickets asking to add X or Y phone.

I might have to develop a way to add plugins! ;-)

**Comment by bdtech** [comment]
Majority of mobile market share is Android, iPhone, and the remainder list above. Feel free to make it configurable or optional if you prefer.

**Comment by maximejobin** [comment]
The problem with "map" is that it impacts EVERY request. That is why I decided to not implement it. I will close this thread as it has derailed from the previous request. If you want to create a specific discussion for mobile detection, please create a new one.
