### ISSUE TITLE
Difference from v1 ?

### ISSUE THREAD

**Issue by neodjandre2** [maximejobin/rocket-nginx#59]
Hi,

What's the actual difference between the previous version of your code? I have v1 running smoothly on my site.. Do I need to upgrade? Are there specific upgrade instructions?

thanks,
Andrew

**Comment by maximejobin** [comment]
Here is the information you are looking for:
https://github.com/maximejobin/rocket-nginx/releases/tag/2.0

**Comment by neodjandre2** [comment]
ok, I am a bit of a newb but how do I uninstall v1.0 ?  

I forgot what files the plugin has added...

many thanks

**Comment by maximejobin** [comment]
You can simply delete the folder `rocket-nginx` and redownload everything. That is the way to "uninstall".
