### ISSUE TITLE
Default nginx config?

### ISSUE THREAD

**Issue by joelataylor** [maximejobin/rocket-nginx#6]
Hi there, was curious if you had a default nginx configuration file for a site to reference?

https://codex.wordpress.org/Nginx - has some good stuff, but curious what you use for your site's conf.

**Comment by maximejobin** [comment]
My configuration is based on what you can find in the Codex. I just added the following documentation:

https://github.com/maximejobin/rocket-nginx/wiki/Nginx-configuration-for-WordPress

Enjoy!

**Comment by joelataylor** [comment]
Thx @maximejobin !!

**Comment by nuevaya** [comment]
Thank you!
