### ISSUE TITLE
Rocket-Nginx and Webuzo-Nginx integration issue

### ISSUE THREAD

**Issue by nik6018** [maximejobin/rocket-nginx#62]
Hi,

I am using Webuzo control panel for my website and they provide Nginx as a Web server so I tried to configure rocket-nginx but with no success.

They compile their Nginx so their conf location is quite different, here is the list
**Main Conf File** : `/usr/local/apps/nginx/etc/nginx.conf`
**Virtual Host File** : `/usr/local/apps/nginx/etc/conf.d/webuzoVH.conf`

The **webuzoVH.conf** file contains the **_server blocks_** for each website, so their support recommended to add the _default.conf_ file in that block for the website that I want.

After adding the conf file I checked and received this in the headers: **X-Rocket-Nginx-Serving-Static:**_No_

So I turned the debug parameter on and it gave me the following information:

**X-Rocket-Nginx-File:**`/home/soft/public_html/wp-content/cache/wp-rocket/109.compilor.com//wp//index.html_gzip`
**X-Rocket-Nginx-Reason**:_File not cached_

My Website has the following path: **/home/soft/public_html/109.compilor.com/wp/**, so can anyone help me so that Rocket-Nginx recognizes the correct path of Website folder.

Also there is no cache folder in my /wp-content folder, can anybody clear my confusion if the file is to be present before or created by Rocket-Nginx.

**Comment by maximejobin** [comment]
A new variable will be needed for your scenario to work properly.

**Comment by maximejobin** [comment]
I'm not even sure I agree with my own comment!!

In the `ini` file, can you try changing to this:

    wp_content_folder = "wp/wp-content"

Then regenerate the configuration file and reload the nginx configuration. Let me know if it works.

**Comment by nik6018** [comment]
@maximejobin  Thanks for the reply, I will test it and let you know.

**Comment by maximejobin** [comment]
It's been more than a month. I'm closing this but feel free to reopen it if you have issues.

**Comment by nik6018** [comment]
@maximejobin  Sorry for the late reply..... but I am still facing the same issue the file is not cached.
Can you let me know any more debugging steps that I can use to check this issue

**Comment by maximejobin** [comment]
What is the value of `X-Rocket-Nginx-File` now in your headers?

Is it the right place where the file is? Otherwise, where is the file on your server?
