### ISSUE TITLE
Will this work with wptouch?

### ISSUE THREAD

**Issue by dantruong460** [maximejobin/rocket-nginx#64]
Will this work good with wptouch?

**Comment by dantruong460** [comment]
Php7

**Comment by maximejobin** [comment]
The script has no impact on your PHP version. Basically, Rocket-Nginx serves files directly without calling PHP and WordPress at all.

I have not tested the script with WPTouch.

**Comment by maximejobin** [comment]
Due to inactivity, this issue will be closed.
