### ISSUE TITLE
Monitoring rocket-nginx in Nginx Amplify?

### ISSUE THREAD

**Issue by haydenjames** [maximejobin/rocket-nginx#65]
Thanks for rocket-nginx its super fast!

Previously I was using Nginx fastcgi cache which worked well, but this is faster. However, of course my cs=$upstream_cache_status no longer works in Nginx Amplify. How can I setup rocket-nginx with Nginx Amplify.. if possible?

Thanks

**Comment by maximejobin** [comment]
Can you give more details about what is not working anymore and what should be changed to make the script better ?  I'm alway open to make it better.

**Comment by haydenjames** [comment]
Sure thing, thanks. 

I followed the guide here (Tip 5 - Configure NGINX for FastCGI)
https://www.nginx.com/blog/9-tips-for-improving-wordpress-performance-with-nginx/#fastcgi

I'm not using Nginx Plus so to purge I used this plugin: 
https://wordpress.org/plugins/nginx-cache/ 

However, once I found your plugin I used this instead. Wp-rocket manages the cache path so it much more seamless now.

However, now with Nginx fastcgi  cache removed I have no graphing of cache hit rate etc:
https://github.com/nginxinc/nginx-amplify-doc/blob/master/amplify-guide.md#cache-metrics

Previously this was done using the access log and customizing the format:
https://amplify.nginx.com/docs/guide-metrics-and-metadata.html#additional-nginx-metrics

I would like to continue to have visual stats of the hit rate/performance of cache.  Here's what it looked like when it worked using Nginx Amplify...

[!alt](https://i.imgur.com/Sdg5n2i.png)

**Comment by maximejobin** [comment]
You seem to know exactly what has to be done. In order to make the process faster, can you tell me, from the generated script, what you would need to be added. Then, I'll make sure I understand the process and validate how it can be added.  I've never played with Amplify so if you show me how it worked in your previous configuration and what exactly we need to add in Rocket-Ngix, I will gladly take a look at what we can do for this request.

From what I understand, it looks like it's about adding the right log at the right place, no ?

**Comment by haydenjames** [comment]
Not exactly. Or I would have contributed code off the bat. I wish.

I believe in order for this to work Rocket Nginx would have to write to the access logs in the format matching $upstream_cache_status using “MISS”, “BYPASS”, “EXPIRED”, “STALE”, “UPDATING”, “REVALIDATED”, or “HIT”. Then Nginx Amplify should be able build graphs from those access log entries. 

I will see what else I can find as well by asking Amplify support.

**Comment by gshulegaard** [comment]
Hi!  Amplify agent contributor here...

For @maximejobin information, the Amplify agent will detect log formats and automatically collect metrics based on NGINX configuration.  @haydenjames already linked our docs repo, but our docs are also available at:

https://amplify.nginx.com/docs

For the "Cache Health" graph @haydenjames was also correct that this graph uses the `$upstream_cache_status` variable from the NGINX Access log.

https://amplify.nginx.com/docs/guide-metrics-and-metadata.html#cache-metrics

For the metric to start populating all that would need to change is your `log_format` setting in the NGINX config.  Amplify will parse the config and use it.

If you need anything else feel free to ask!  We also do monitor our github issues at:

https://github.com/nginxinc/nginx-amplify-agent/

And our Amplify UI has Intercom chat embedded so you can also reach us that way.

**Comment by maximejobin** [comment]
@haydenjames You closed the issue. Can you clarify why ? Were you able to solve your issue without needing Rocket-Nginx to be edited ? If so, can you please leave here an explanation for future users ?

@gshulegaard Thank you very much for taking the time to write here. I will definitely check the doc and the other links your posted. I appreciate the time you took. And if you have a proposal for Rocket-Nginx, I'll gladly consider it! :)

**Comment by gshulegaard** [comment]
@maximejobin Thanks for the kind words!  But I was just trying to help add additional information and open the door for additional support/questions.

NGINX Amplify is meant to be a complimentary monitoring service for NGINX. I would be happy to work with you to determine what Rocket-Nginx users would be most interested in monitoring and I could suggest NGINX configuration changes/values that would allow the Amplify agent to collect this information.

If interested, I would also be happy organize a reference doc you could link/put in your docs that could walk users through setting up monitoring for Rocket-Nginx with Amplify (detailing some advanced features such as Dashboards and Filters which require some user configuration).  I am not in charge of our blog, but if you are interested I could pitch a guest/collaborative blog post talking about Rocket-Nginx and performance monitoring with Amplify.

**Comment by maximejobin** [comment]
I would love to collaborate and make Rocket-Nginx support Amplify.

Let me know if you need anything to understand how Rocket-Nginx work. I'd be happy to assist you and explain further.

**Comment by gshulegaard** [comment]
@maximejobin I just moved this discussion to a different issue :)
