### ISSUE TITLE
CDN Support

### ISSUE THREAD

**Issue by Arjoni** [maximejobin/rocket-nginx#66]
I am using WP-Rocket with CloudFront. Is there a way to add CDN support to the nginx config? I am using cdn.domain.com as the CDN subdomain. 

Thank you!

**Comment by maximejobin** [comment]
> Is there a way to add CDN support to the nginx config?

What do you mean exactly by "add support" ?

**Comment by Arjoni** [comment]
Configuration doesn't work if the user adds CDN at wp-rocket dashboard.

**Comment by maximejobin** [comment]
You have to be specific about what you are saying.  "It doesn't work" is not enough to help you.

What is the expected outcome? 
What are you getting? 
What is your exact configuration?
What is your website exactly ?

There are so many possibilities out there, you must be really specific. Otherwise, it's simply impossible for me to guess what is wrong (if anything).

**Comment by Arjoni** [comment]
Sorry for not providing enough information. 
When you activate CDN setting for WP Rocket, images and other files are moved to the CDN subdomain (cdn.enterprise.com.al). Files are not received and displayed when using the CDN option. Website is not displayed as it should because CSS, JS and pictures are not received from CDN.

**Comment by maximejobin** [comment]
I understand you did activate the option inside WP-Rocket.

Now, did you configure anything else ?

You need to configure the subdomain accordingly. Then, include the script once again in that configuration.

Please give the exact steps of what you did and where is the problem.

**Comment by Arjoni** [comment]
I just activated the CDN option and added the CDN subdomain. I didn't do anything else. 

What do you mean by "You need to configure the subdomain accordingly"? CloudFront CDN is configured and the CDN subdomain is added at configuration of WP Rocket. 

Do I need to add extra configuration on nginx? I have added "include rocket-nginx/default.conf;" on vhost config.

**Comment by maximejobin** [comment]
Rocket-Nginx simply optimizes the way to serve static files.  Nothing more, nothing less. You have to follow the directives given by Cloudfront to do the setup properly.

It looks like you did not configure at all your website to work properly with a CDN.

**Comment by efelinto** [comment]
Hello Maxime,

Thank you for your support.
I'm currently using Engintron in cPanel, which you should know about. It by default by Microcache does just that, it serves the html file directly without calling PHP. I've already disabled PHP for a test and the pages that were cached before continued to load perfectly.
However I have to keep the microcache time small, currently it's 15s, which is slightly high. I would like as soon as the user gives the command for WP-Rocket to clear the cache, Nginx automatically clears the cache for that domain. Would it be possible ?
Please help me with this setup.

**Comment by maximejobin** [comment]
Due to inactivity, this issue will be closed.
