### ISSUE TITLE
browser media extensions not populated

### ISSUE THREAD

**Issue by rmuthukrishnan** [maximejobin/rocket-nginx#67]
Hi, Thank you for providing this configuration file.

In the latest version, I cloned the repository and ran the php script. I see the media extensions is not populated below:

# BROWSER MEDIA CACHE
#
location ~* \.()$ {
    etag on;
    expires 30d;
}

In version 1.1, it is the following:
 
  # BROWSER MEDIA CACHE                                                               
  #                                                                                   
  location ~* \.(ico|gif|jpe?g|png|svg|eot|otf|woff|woff2|ttf|ogg)$ {
      expires max;
      add_header Cache-Control "public";                                              
      add_header Access-Control-Allow-Origin "*";
  }

Could you check? I see the template file does have the media extensions. I did not modify any of the files.

Thank you,
Raman

**Comment by maximejobin** [comment]
Did you follow instructions here:
https://github.com/maximejobin/rocket-nginx#installation

My guess is that you did not rename the `ini` file (removing the `.disabled`).

Let me know if I was right.

**Comment by rmuthukrishnan** [comment]
Hi Maxime,

Thank you for your response.
I did follow the instructions.
Copying or moving rocket-nginx.ini.disabled to rocket-nginx.ini gives the same result for me.

I found one issue:
The rocket-nginx.ini has the key name as media_extensions while the rocket_parser.php had it as medias_extension. I corrected that in rocket_parser.php, but then the check for is_array on that is failing.

Raman
________________________________

**Comment by maximejobin** [comment]
I was able to reproduce the problem. A new version will be released.

**Comment by maximejobin** [comment]
Fixed.
