### ISSUE TITLE
Question: nginx serving two wordpress sites

### ISSUE THREAD

**Issue by rmuthukrishnan** [maximejobin/rocket-nginx#68]
Hi Maxime,

Two questions:
1. I have two wordpress sites each in a separate directory and is served by same nginx.
       /web/
       /store/
    Both have wp-rocket plugin enabled.
    How can I set the $rocket_url to point to the correct cache folder?
    I thought I can put that inside location directive, but it appears the if-statements get evaluated first. So, I am thinking of puting a regex on the uri_request to check if the uri starts with /web/ or /store/ to point to the right cache. Is that approach correct?

2. I see the $rocket_file always points to index_html.https.gzip. Is not wordpress bypassed for other web pages?

Thank you for your help,
Raman

**Comment by mathieu-aubin** [comment]
Wouldn't this take care of itself if they are both served under different server blocks?

**Comment by maximejobin** [comment]
1. I don't see why it wouldn't work as-is. Otherwise, you could have 2 different configurations (1 per site) if needed.

2. That is the way WP-Rocket works. They always call the file "index". If only your homepage is using the static file, then you have a problem. It might be the way you configured your website because it should work correctly.

Let me know if you have other questions.

**Comment by rmuthukrishnan** [comment]
Thank you very much for your answers.
The path of wp-content is different for the sites. So, your idea of 2 different rocket-nginx.conf will work. I will need to select it using if-statement to see if the $request_uri is accessing which sub-directory.

Also, a separate server block and having different rocket-nginx.conf for each server block, as Mathieu suggested, will work. Only thing is in this solution I will need to map the subdirectory to a domain name as the server_name does not seem to accept slashes.

Thank you again,
Raman
________________________________

**Comment by maximejobin** [comment]
You don't need a "if". Rocket-Nginx 2.x enables you to generate multiple configurations.

In the ini file, at the end, you can add:

    [myotherconfig : default]
    
    ; WP-Content folder
    ; Default value: wp-content
    wp_content_folder = wp-content-number-2

Then, re-run the parser and you'll end up with 2 files
- default.conf
- myotherconfig.conf

Simply include the first configuration in one website and the second one in the other!

**Comment by maximejobin** [comment]
Due to inactivity, this issue will be closed.
