### ISSUE TITLE
Rocket-Nginx + Engintron

### ISSUE THREAD

**Issue by efelinto** [maximejobin/rocket-nginx#73]
Hello Maxime,

Thank you for your support.
I'm currently using Engintron in cPanel, which you should know about. It by default by Microcache does just that, it serves the html file directly without calling PHP. I've already disabled PHP for a test and the pages that were cached before continued to load perfectly.
However I have to keep the microcache time small, currently it's 15s, which is slightly high. I would like as soon as the user gives the command for WP-Rocket to clear the cache, Nginx automatically clears the cache for that domain. Would it be possible ?
Please help me with this setup.

**Comment by maximejobin** [comment]
Basically, you want to do with Engintron exactly what Rocket-Nginx does with WP-Rocket. My recommendation is to use Rocket-Nginx instead of Engintron for that purpose.

If you want to link WP-Rocket and Engintron, you are not asking support to the right project.

**Comment by efelinto** [comment]
I'm using cPanel and the choice of Engintron is due to its full compatibility with cPanel. Can not you pass me any code I have to add to nginx.conf, or similar so that when a site cleans the wp-rocket cache, the nginx cache is also cleared?

**Comment by maximejobin** [comment]
It doesn't work like that. Rocket-Nginx does not touch the Nginx cache. Nginx manages itself automatically from the altered request from Rocket-Nginx.

**Comment by efelinto** [comment]
What cache system does Rocket-nginx use then?

**Comment by maximejobin** [comment]
It doesn't use any. It lets Nginx manage the caching automatically. Nginx reads the files from the disk and put them in RAM to serve them faster. There is nothing to do.
