### ISSUE TITLE
Issue with WordPress Multisite in Directory mode

### ISSUE THREAD

**Issue by lbeckerfive** [maximejobin/rocket-nginx#74]
Copy of closed issue: 
https://github.com/maximejobin/rocket-nginx/issues/33#issuecomment-340026976

There seems to be an issue where the cached file retrieval is incomplete for Directory sites in a Multisite environment. I can't see why because these appear like regular folders in wp-content/cache/wp-rocket/ so you would think they are handled the same way. I know I had to set WP Rocket up for each site. Maybe a permalink type confusion?

Your directive works fine for the root site. It works fine for subdomains in multisite. But when we try it on Directory sites in Multisite, it loads parts of the pages.

Any insight is greatly appreciated. Let me know if there's anything I can do to help identify the problem.

Here the details you asked before. ( "test.de" Domain is not the real name. It's a customer page and I don't want to paste them here ;-) )
x-rocket-nginx-file:/var/www/vhosts/test.de/httpdocs/test.de/wp-content/cache/wp-rocket/test.de//fr//index-https.html
x-rocket-nginx-reason:/wp-content/cache/wp-rocket/test.de//fr//index-https.html
x-rocket-nginx-serving-static:Yes

Normal without adding configuration: HTTP 200 - the correct page
With Rocket-Nginx Configuration: HTTP 404 - File not found

**Comment by maximejobin** [comment]
Sorry for the delay.

Do you know what should be the expected static file that should be served? I don't have a multisite setup right now so if you can help and give more details, it would be great.

**Comment by maximejobin** [comment]
I have reopend the other issue. Let's close this one.
