### ISSUE TITLE
Can it use redis object cache + nginx help + wp-rocket + rocket-nginx together

### ISSUE THREAD

**Issue by thanh25896** [maximejobin/rocket-nginx#78]
My site is using redis server and some plugin cache like redis object cache + nginx helper + wp-rocket + rocket-nginx .  To my knowledge redis is object cache , wp-rocket is page cache and I can use them together without conflicts right?
1 more question : Is varnish cache and rocket-nginx is the same cache technique but varnish cache on ram and rocket-nginx cache on disk right? Yesterday I tried to use varnish on my site but I can't config varnish for SSL site and with my knowledge if I use varnish for SSL site varnish need to do more job than rocket-nginx because the proxy . I don't know it is right or not but if I right the rocket-nginx will faster than varnish on SSL site although varnish use ram cache but it will take more job for cpu, ram .......

My crontab set in nginx "*/15 * * * * cd /home/*/public_html; php wp-cron.php &>/dev/null" is right?

Can you explain all of my question completely? Sorry for my curious and thank you for reading it and explain !

**Comment by maximejobin** [comment]
Rocket-Nginx should not conflict with Redis.

Rocket-Nginx and Varnish are similar. The advantage Rocket-Nginx has is that it is tighly coupled with your WP-Rocket configuration. You don't have to setup rules like you have to do in Varnish (Varnish Configuration Language - VCL). That is, in my opinion, an advantage for 90-95% of the use cases.

Rocket-Nginx serves the files that are on disk, true. But Nginx has its own caching and already stores them in memory already. In conclusion, it would be false to say that it is "disk vs memory" caching.

Your crontab seems to be missing a "*" at the beginning.

I hope it answers everything.

**Comment by thanh25896** [comment]
I hope I understood correctly what you say. As far as I understand : 
Rocket-Nginx not confict with redis . That mean I can use rocket-nginx with redis + redis object cache plugin and nginx helper plugin . Do you have any idea to use redis more effective like database cache + object cache with redis ? I just can use the object cache with plugin "redis object cache"

In my opinion i think varnish is very complex when config for SSL site .  But if I can config varnish run with ssl site completely it will slower and use more job than rocket-nginx ((use more cpu) because of proxy (is it right?)
Is wp-rocket and Rocket-nginx only the page cache and browser cache? If right I can you other method (database cache, object cache) with redis or memcached? Are the redis and memcached similar on wordpress ( nothing difference )? The redis config more complex than memcached.

Does Rocket-Nginx work only with wp-rocket plugin ? If I use other cache plugin like w3tc Rocket-Nginx won't work right?

**Comment by maximejobin** [comment]
> Rocket-Nginx not confict with redis . That mean I can use rocket-nginx with redis + redis object cache plugin and nginx helper plugin . Do you have any idea to use redis more effective like database cache + object cache with redis ? I just can use the object cache with plugin "redis object cache"

That is correct.

>In my opinion i think varnish is very complex when config for SSL site . But if I can config varnish run with ssl site completely it will slower and use more job than rocket-nginx ((use more cpu) because of proxy (is it right?)

I honestly cannot comment on that. I did not benchmark Varnish vs Rocket-Nginx.

> Is wp-rocket and Rocket-nginx only the page cache and browser cache?

Yes

>If right I can you other method (database cache, object cache) with redis or memcached?

Yes

>Does Rocket-Nginx work only with wp-rocket plugin ? If I use other cache plugin like w3tc Rocket-Nginx won't work right?

Rocket-Nginx **only** works with WP-Rocket and Nginx.

**Comment by thanh25896** [comment]
Thank you for answer me !

I still have question about redis and memcache can you help me ( I know this forum about nginx-rocket)?
Are the redis and memcached similar on wordpress ( nothing difference )? To my knowledge redis can cache more kind of database but some of my friends said they have a problem about slow down website after a few month of redis run on wordpress  (may be they used wrong config ) but I didn't hear someone tell about the problem with memcached.
