### ISSUE TITLE
woocommerce_items_in_cart

### ISSUE THREAD

**Issue by rmuthukrishnan** [maximejobin/rocket-nginx#79]
Hi Maxime,

Just FYI:

For woocommerce, I also had to add the following so that wp-rocket is not bypassed when items are in the cart:

if ( $cookie_woocommerce_items_in_cart = "1" ){
    set $rocket_bypass 0;
    set $rocket_reason "Cart cookie";
}

Thank you,
Raman

**Comment by maximejobin** [comment]
Rocket-Nginx already supports this cookie. Did you have a problem with it ?

See in the configuration:
https://github.com/maximejobin/rocket-nginx/blob/master/rocket-nginx.ini.disabled#L31

**Comment by maximejobin** [comment]
Some people did report 404. That is why it was added. It fixed the problem.

**Comment by rmuthukrishnan** [comment]
Hi Maxime,

Thank you very much for the answer. Currently, I did not include that as I do not seem to have that issue.
