### ISSUE TITLE
"File not cached" - Unable to identify reason for this issue

### ISSUE THREAD

**Issue by bbbenji** [maximejobin/rocket-nginx#81]
The cache directory `/srv/REDACTED/www/wp-content/cache/` is writeable. However, the `wp-rocket` directory is never created.

Reading through previous issues I saw someone resolved their issue by placing the `rocket-nginx` include inside the php block, this did not make a difference for me.

I am using Cloudflare, however I have set it to Maintenance Mode.
I do not have a `.maintenance` file.
I am not logged in, tried different browsers as well as online http header checkers.
Checked as a mobile and desktop user.

Unable to figure this one out.

```
cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
content-encoding: br
content-type: text/html; charset=UTF-8
date: Mon, 09 Apr 2018 09:38:48 GMT
expires: Thu, 19 Nov 1981 08:52:00 GMT
link: <https://wp.me/P6CQF5-rh>; rel=shortlink
link: <https://REDACTED.pl/wp-json/>; rel="https://api.w.org/"
pragma: no-cache
server: nginx
status: 200
vary: Accept-Encoding
x-rocket-nginx-file: /srv/REDACTED.pl/www/wp-content/cache/wp-rocket/REDACTED.pl///index-https.html
x-rocket-nginx-reason: File not cached
x-rocket-nginx-serving-static: No
x-ua-compatible: IE=edge
```

nginx.conf: https://hastebin.com/vowasakeze.nginx
default.conf: https://hastebin.com/ucilirizag.nginx

**Comment by maximejobin** [comment]
Rocket-Nginx does not create any file or directory.  If nothing is created, it is because of a problem with WP-Rocket or your web hosting configuration. I suggest you contact WP-Rocket for that.
