### ISSUE TITLE
Serve Common Cache for Subscribers

### ISSUE THREAD

**Issue by royashgit** [maximejobin/rocket-nginx#84]
Hi,

Is it possible to serve a common cache for all subscribers (excluding profile pages etc.) ?

This would be very useful for our membership site with restricted content. 

many thanks,
Andrew

**Comment by maximejobin** [comment]
Nothing was implemented to create a "per user" cache which is an option offered by WP-Rocket. The "common cache for all subscribers" is not a functionality offered by WP-Rocket... therefore it is not supported.
