### ISSUE TITLE
Incorrect cache directory

### ISSUE THREAD

**Issue by DavidRSW** [maximejobin/rocket-nginx#85]
Hi,

I have a problem, rocket-nginx will look for the file to a path that does not exist.

X-ROCKET-NGINX-SERVING-STATIC -> NO
X-ROCKET-NGINX-REASON -> File not cached (Yes it is cached, but the route is different!)
X-ROCKET-NGINX-FILE -> /etc/nginx/html/var/www/web.com ...

The correct route is /var/www/web.com .. but always force /etc/nginx/html first.

; WP-Content folder
; Default value: wp-content
wp_content_folder = /var/www/web.com/web/wp-content it does not work :(

PS: Apache Web Server + NGINX as Reverse Proxy

Any solution? Thank you

**Comment by DavidRSW** [comment]
OK, partly solved.

You must specify the path in the nginx vhost:

`root /var/www/web.com ;`

I did not have it that way because when using it as a proxy is not necessary, proxy_pass is used.

But now header "x-rocket-nginx" has disappeared, only x-rocket-nginx NO appears in the wp-admin. users do not see x-rocket-nginx Yes, but I think it works, because it works very fast...

**Comment by maximejobin** [comment]
If you are logged in, the cache is never served from Rocket-Nginx.

You can activate [debug](https://github.com/maximejobin/rocket-nginx#debug) mode to know why the cached file is not served.
