### ISSUE TITLE
Rocket-Nginx .conf File Not Loading with Engintron

### ISSUE THREAD

**Issue by MojoCreator** [maximejobin/rocket-nginx#86]
I am using Engintron on cpanel/whm (https://github.com/engintron/engintron) . When i test with nginx -t, it doesn't show the .conf file, it only shows the default result below.

nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

I have tried to add the following to the default.conf and restart nginx/apache (seen screenshot, https://www.screencast.com/t/vetY1tRePuA0)

# Rocket-Nginx configuration
    include /etc/nginx/rocket-nginx/default.conf;

and 

# Rocket-Nginx configuration
    include rocket-nginx/default.conf;

Any idea why its not loading?
Thanks for the help.

**Comment by maximejobin** [comment]
We have not tested on Engintron so I don't have an answer for you.

If you would like commercial support, feel free to email support@satellitewp.com and someone will gladly help you.

I hope it helped.

**Comment by MojoCreator** [comment]
@maximejobin - here is your answer - https://github.com/engintron/engintron/issues/917#issuecomment-417663303

**Comment by maximejobin** [comment]
Their answer makes sense to me. Thank you for the link!
