### ISSUE TITLE
Possible to use this for an Nginx/Apache stack?

### ISSUE THREAD

**Issue by tannerchung** [maximejobin/rocket-nginx#87]
I'm currently trying to enable fastcgi _or_ use rocket-nginx to utilize nginx caching. My server is an Nginx/Apache stack and I'm trying to figure out where to include the generated `rocket-nginx/default.conf` file but there is no `sites-available` directory under /etc/nginx. Is it possible to configure this with the current server stack?

**Comment by Dibbyo456** [comment]
RunCloud?

**Comment by maximejobin** [comment]
If you are using Nginx as a reverse proxy, there is no point to use Rocket-Nginx.

**Comment by Dibbyo456** [comment]
Aww.. I was gonna ask this question later today. Thank you.

**Comment by slomeli79** [comment]
> If you are using Nginx as a reverse proxy, there is no point to use Rocket-Nginx.

For clarity, is it accurate then to say that an Apache server with NGINX reverse proxy would perform as well as an NGINX server using Rocket-NGINX? (WP Rocket in use in both scenarios) That is my takeaway from the above statement.

I'm using Runcloud as well, so I can switch between Apache/NGINX-hybrid and native NGINX. But from the above, it sounds like setting up rocket-nginx in the NGINX configuration is a hassle and that using the hybrid would perform just as well.

**Comment by maximejobin** [comment]
> > If you are using Nginx as a reverse proxy, there is no point to use Rocket-Nginx.

That is not totally true and really depends on how it was configured.

> For clarity, is it accurate then to say that an Apache server with NGINX reverse proxy would perform as well as an NGINX server using Rocket-NGINX? (WP Rocket in use in both scenarios) That is my takeaway from the above statement.

No, it's two different things. It really depends on how you "reverse proxy" is configured. Using Rocket-Nginx will serve the cached file directly without any PHP execution. Using Apache + Nginx will never do that out of the box.

> I'm using Runcloud as well, so I can switch between Apache/NGINX-hybrid and native NGINX.

We use RunCloud and it works really well with Rocket-Nginx

> But from the above, it sounds like setting up rocket-nginx in Runcloud's NGINX configuration is a hassle and that using the hybrid would perform just as well.

It is now super easy and can be done directly from your RunCloud dashboard. Just pick the `location.main-before` option in the dropdown and paste your include there. When you save, it will reload your configuration and you'll be good to go!

With the new Nginx configuration

**Comment by slomeli79** [comment]
> It is now super easy and can be done directly from your RunCloud dashboard. **Just pick the `location.main-before` option** in the dropdown and paste your include there. When you save, it will reload your configuration and you'll be good to go!

^ That was precisely the detail I couldn't find anywhere. Off to implement now - Thanks!

**Comment by maximejobin** [comment]
Awesome!

**Comment by beamkiller** [comment]
I'm glad I found this thread :)
I was able to install and add it to RunCloud.

My question is if the the Rocket Nginx is updated how can we update it on our server too?

**Comment by maximejobin** [comment]
You have to run `git pull`. Then adjust the configuration if needed and run the PHP parser again.

Finally, reload the Nginx configuration. It is basically the same steps as when you installed it but instead of cloning, you pull the repo. And instead of making a copy of the ini file, you adjust the previously created file.
