### ISSUE TITLE
Using Rocket-Nginx w/ nDeploy on CentOS & cPanel/WHM Server

### ISSUE THREAD

**Issue by brianjking** [maximejobin/rocket-nginx#9]
Hello,

I have a few sites that are using Nginx w/ PHP-FPM & WordPress w/ WP-Rocket's plugin installed. I'm on a CentOS 6 server using nDeploy (see links below) which handles my NGINX & PHP-FPM installation & basic configurations. 

I'm trying to figure out how to configure this to work in this setup, however, I'm having some trouble when adding to my nginx.conf file.

Can you please take a look at how nDeploy works and see if you can please help me out?

Thanks!

https://support.sysally.net/projects/ndeploy/wiki
https://github.com/AnoopAlias/nDeploy

**Comment by maximejobin** [comment]
Do you have a specific question ?
What did you try ?

See if you can add specific "rules" to your Nginx configuration and add the Rocket-Nginx configuration.

I am not familiar with nDeploy.

**Comment by maximejobin** [comment]
No details added.
