### ISSUE TITLE
Headers do not support the "always" keyword

### ISSUE THREAD

**Issue by maximejobin** [maximejobin/rocket-nginx#90]
Add support for the "always" keyword in `add_header`.

More information can be found (an example) in the issue #89 .

**Comment by kevin25** [comment]
Can you please support static compression either?

**Comment by maximejobin** [comment]
@kevin25 Can you be more specific about your needs by opening another ticket and giving more details?

**Comment by maximejobin** [comment]
Code is completed for this feature.
