### ISSUE TITLE
Wrong cache indicator

### ISSUE THREAD

**Issue by kevin25** [maximejobin/rocket-nginx#91]
Hi Maxim,

I upgraded my Wp-rocket to 3.2 today and enabled the mobile cache either. I found out that there is something wrong with nginx cache.

> x-rocket-nginx-serving-static: No

<img width="625" alt="screen shot 2018-11-07 at 21 06 40" src="https://user-images.githubusercontent.com/2909982/48136498-63318780-e2d2-11e8-8d3c-b5014cf24eb6.png">

Even the cache files are there. There path is also valid.

<img width="1199" alt="screen shot 2018-11-07 at 21 10 33" src="https://user-images.githubusercontent.com/2909982/48136519-717fa380-e2d2-11e8-8e13-d9f979e6c789.png">

**Comment by maximejobin** [comment]
Have you activated the "mobile cache" in the WP Rocket settings ? If so, there is no way for Rocket-Nginx to know if it must serve the mobile or desktop cache. That is why it doesn't serve it directly.

**Comment by kevin25** [comment]
@maximejobin Yes, I enabled it. So I have to disable it so that it can work again?

**Comment by maximejobin** [comment]
If your theme is responsive (most themes are), you shouldn't enable this option.

If you have one layout for mobile that is different from the desktop's layout (meaning it's basically two totally different pages), then you should activate this option.

**Comment by kevin25** [comment]
My theme is responsive. I disabled it now but it didn't still work. Do I need to clear all cache and start preloading again?

**Comment by maximejobin** [comment]
Yes, you should.

**Comment by maximejobin** [comment]
What version of Rocket-Nginx are you using ?

Can you give the URL you are testing ?

**Comment by kevin25** [comment]
I used the master brand. Should I use the 2.0 instead?

**Comment by maximejobin** [comment]
Master is the right branch to use.
