### ISSUE TITLE
Serve static html even have items in cart

### ISSUE THREAD

**Issue by kevin25** [maximejobin/rocket-nginx#92]
Whenever customer has item in cart, nginx stops server html file. The idea is still serve it while exclude the cart. Do you think it's possible?

**Comment by kevin25** [comment]
Any update on this, @maximejobin?

**Comment by maximejobin** [comment]
Your question is related to your theme and/or WP-Rocket. It has nothing to do with Rocket-Nginx. WP-Rocket already manages the fact that the cart should not be put in cache. If it's not in cache, Rocket-Nginx won't serve the static file as it won't exist.

**Comment by kevin25** [comment]
Thank you for clarifying it. I'll ask them about this.
