### ISSUE TITLE
Question - How can I configure it to accept Brotli?

### ISSUE THREAD

**Issue by kevin25** [maximejobin/rocket-nginx#93]
I installed and configured Brotli but i didn't see the header. What should I do to make it work with rocket-nginx?

# Is Brotli accepted by client ?
> if ($http_accept_encoding ~ br) {
>         set $rocket_encryption "";
> }

**Comment by maximejobin** [comment]
There is nothing to do. If Brotli is detected and enable on your server, it will be used.

**Comment by kevin25** [comment]
Thank you. I got it.
