### ISSUE TITLE
sub_filter is not working

### ISSUE THREAD

**Issue by ch1efmaster** [maximejobin/rocket-nginx#95]
Hello.

I have a problem with sub_filter 
It is not working in site-nginx.conf and rocket-nginx conf.

I hope you can help me with this problem.
Have a nice day.

**Comment by ch1efmaster** [comment]
For the test, I use the standard Nginx configuration for WordPress .
I need to change the theme name and time zone.

Example:
sub_filter 'ThemeName_v5.5.3' 'MyThemeName';
sub_filter '+00: 00 "' '' +03: 00" ';
sub_filter_once off;

Since the pages are packed in gzip format, Nginx cannot replace them.

**Comment by maximejobin** [comment]
This does not help. Please include all your configuration files for that site.

Thank you.
