### ISSUE TITLE
nginx: [emerg] unknown "rocket_args_tmp" variable

### ISSUE THREAD

**Issue by kevin25** [maximejobin/rocket-nginx#96]
Hey Max,

I tested with the 2.2 and got that warning

> nginx: [emerg] unknown "rocket_args_tmp" variable

**Comment by fovos** [comment]
Hi maxmejobin!

I have the same problem. I have already used the master version of it and it works like a charm! 

However i wanted to try the 2.2 branch. I deployed it the same way as the master. Created the default.conf file but the nginx -t return failure : nginx: [emerg] unknown "rocket_args_tmp" variable .

Do you have any idea? Thanks in advance.

**Comment by maximejobin** [comment]
@fovos Branch 2.2 is a development branch and is not ready. It should not be used at this point.

**Comment by fovos** [comment]
Thank you for your response. 

So i guess there is no way at the moment to get over the query strings problem, right?
