### ISSUE TITLE
Wordpress is not bypassed

### ISSUE THREAD

**Issue by TheHusnain** [maximejobin/rocket-nginx#97]
The only cached page served without Wordpress intervening first is the home page. All other pages have the below headers.

```
x-rocket-nginx-reason: File not cached
x-rocket-nginx-serving-static: No
```

The cached pages are available in /wp-content/cache/wp-rocket/ and seem to be served through Wordpress but x-rocket-nginx-serving-static is always set to 'No'.

**Comment by maximejobin** [comment]
Can you give the site URL you are testing ?

**Comment by TheHusnain** [comment]
Of course, it's https://bit.ly/2AJ1F5s
Thank you.

**Comment by TheHusnain** [comment]
Solved. It turns out that it was my NGINX configuration causing the issue.

I had the following in my default.conf:

```
location / {
        try_files $uri $uri/ /index.php?q=$uri$args;
}
```

As a result, wp-rocket created an additional directory within the appropriate directory to store the cache file.

For example, it stored the cached HTML for the 'about' page as:
`/cache/wp-rocket/example.com/about/q=%2fabout%2f/index-https.html_gzip.`
However, it should've been:
`/cache/wp-rocket/example.com/about/index-https.html_gzip.`

**Comment by TheHusnain** [comment]
Solved. It turns out that it was my NGINX configuration causing the issue.

I had the following in my default.conf:

location / {
        try_files $uri $uri/ /index.php?q=$uri$args;
}
As a result, wp-rocket created an additional directory within the appropriate directory to store the cache file.

For example, it stored the cached HTML for the 'about' page as:
/cache/wp-rocket/example.com/about/q=%2fabout%2f/index-https.html_gzip.

However, it should've been:
/cache/wp-rocket/example.com/about/index-https.html_gzip.

**Comment by TheHusnain** [comment]
Solved. It turns out that it was my NGINX configuration causing the issue.

I had the following in my default.conf:

```
location / {
        try_files $uri $uri/ /index.php?q=$uri$args;
}
```
As a result, wp-rocket created an additional directory within the appropriate directory to store the cache file.

For example, it stored the cached HTML for the 'about' page as:
`/cache/wp-rocket/example.com/about/q=%2fabout%2f/index-https.html_gzip.`

However, it should've been:
`/cache/wp-rocket/example.com/about/index-https.html_gzip.`
