### ISSUE TITLE
Cache is not working when we enable separate mobile cache, how can we enable nginx to detect mobile and desktop client.

### ISSUE THREAD

**Issue by sandy141414** [maximejobin/rocket-nginx#99]
Cache is not working when we enable separate mobile cache, how can we enable to detect mobile and desktop client.

last-modified: Sun, 30 Dec 2018 15:10:26 GMT
server: nginx
status: 200
strict-transport-security: max-age=31536000
vary: Accept-Encoding
x-content-type-options: nosniff
x-rocket-nginx-file: /home/admin/web/pagalparrot.com/public_html/wp-content/cache/wp-rocket/www.pagalparrot.com//manmohan-singh-refuses-comment-accidental-prime-minister-movie//index-https.html
x-rocket-nginx-reason: Specific mobile cache activated
x-rocket-nginx-serving-static: No

**Comment by sandy141414** [comment]
With this hack ( https://github.com/maximejobin/rocket-nginx/pull/83 ) , nginx is serving separate files for desktop and mobile clients, only bug is that its not changing the header x-rocket-nginx-serving-static: , i have tested its showing different path for respected request.
https://github.com/maximejobin/rocket-nginx/pull/83

**Comment by maximejobin** [comment]
I'm sorry but I can't help if you don't provide asked information.

The hack you are referring to works partially. If you are good with it, that is totally fine! :)

**Comment by faizan47** [comment]
> The hack you are referring to works partially. If you are good with it, that is totally fine! :)

Sorry to jump in but I faced this issue as well.

Some plugins like [https://codecanyon.net/item/easy-social-share-buttons-for-wordpress/6394476](this) need to have separate mobile caching enabled. Is there not a way to make it work with rocket nginx? 

There is a solution [https://docs.wp-rocket.me/article/663-mobile-cache-desktop-view-displayed-for-mobile-devices](here by WP Rocket) but I think it will cause performance issues.

**Comment by maximejobin** [comment]
@faizan47 There is no way as of right now to make it work. That being said, an "experimental" detection could be added for Android and iPhone/iPad/iPod. That would cover most of the market but surely won't be perfect.

Detecting mobile device is a science... that is why I stopped the project of trying to detect the kind of device after a couple of hours of research/code.

**Comment by maximejobin** [comment]
@faizan47 The "official solution" is not clear as you probably did not notice the notice at the top:

> Note: Since WP Rocket 2.8.11, if you're using our NGINX configuration, **_you don't have to do anything._**
